# app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app-image-pull
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/x81k25/test-app-image-pull
    targetRevision: HEAD
    path: k8s
    helm:
      parameters:
      - name: imageCredentials.username
        value: x81k25
      - name: imageCredentials.password
        value: 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
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 2
      backoff:
        duration: "5s"
        factor: 2
        maxDuration: "1m"