# pgsql/overlays/dev/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namePrefix: dev-
patches:
- patch: |-
    apiVersion: apps/v1
    kind: StatefulSet
    metadata:
      name: postgres
      namespace: pgsql
    spec:
      template:
        metadata:
          labels:
            app: postgres
            environment: dev
        spec:
          containers:
          - name: postgres
            env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: pgsql-dev-config
                  key: pgsql_dev_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgsql-dev-config
                  key: pgsql_dev_password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: pgsql-dev-config
                  key: pgsql_dev_database
          volumes:
          - name: postgres-data
            hostPath:
              path: /d/postgres/dev
              type: DirectoryOrCreate
  target:
    kind: StatefulSet
    name: postgres
    namespace: pgsql
- patch: |-
    apiVersion: v1
    kind: Service
    metadata:
      name: postgres
      namespace: pgsql
    spec:
      $patch: replace
      type: NodePort
      ports:
      - port: 5434
        targetPort: 5432
        nodePort: 31434
        name: postgres
        protocol: TCP
      selector:
        app: postgres
        environment: dev
  target:
    kind: Service
    name: postgres
    namespace: pgsql