# dagster/overlays/prod/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media-prod
resources:
- ../../base
nameSuffix: -prod
commonLabels:
  variant: prod
  environment: prod

patches:
# Dagster Deployment Patch
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: dagster
    spec:
      template:
        spec:
          containers:
          - name: dagster-dagit
            envFrom:
            - configMapRef:
                name: environment
            - configMapRef:
                name: wst-config
            - secretRef:
                name: wst-secrets
            - configMapRef:
                name: dagster-config
            - secretRef:
                name: dagster-secrets
            env:
            - name: DAGSTER_K8S_PIPELINE_RUN_NAMESPACE
              value: media-prod
          - name: dagster-daemon
            envFrom:
            - configMapRef:
                name: environment
            - configMapRef:
                name: wst-config
            - secretRef:
                name: wst-secrets
            - configMapRef:
                name: dagster-config
            - secretRef:
                name: dagster-secrets
            env:
            - name: DAGSTER_K8S_PIPELINE_RUN_NAMESPACE
              value: media-prod
          - name: git-sync
            env:
            - name: GITSYNC_REF
              value: "main"
          initContainers:
          - name: git-sync-init
            env:
            - name: GITSYNC_REF
              value: "main"
          volumes:
          - name: dagster-home
            hostPath:
              path: /d/k8s/volumes/dagster/prod/home
              type: DirectoryOrCreate
          - name: dagster-workspace
            hostPath:
              path: /d/k8s/volumes/dagster/prod/workspace
              type: DirectoryOrCreate

# Dagster Service Patch
- target:
    version: v1
    kind: Service
    name: dagster
  patch: |-
    - op: replace
      path: /spec/ports/0/nodePort
      value: 30300