# dagster/overlays/prod/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media-prod
resources:
- ../../base
nameSuffix: -prod
commonLabels:
  variant: prod
  environment: prod

patches:
# Dagster Deployment Patch
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: dagster
    spec:
      template:
        spec:
          containers:
          - name: dagster-dagit
            env:
            - name: DAGSTER_PG_USERNAME
              valueFrom:
                secretKeyRef:
                  name: dagster-pgsql-config
                  key: PGSQL_USER
            - name: DAGSTER_PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dagster-pgsql-config
                  key: PGSQL_PASSWORD
            - name: DAGSTER_PG_HOST
              valueFrom:
                secretKeyRef:
                  name: dagster-pgsql-config
                  key: PGSQL_HOST
            - name: DAGSTER_PG_PORT
              valueFrom:
                secretKeyRef:
                  name: dagster-pgsql-config
                  key: PGSQL_PORT
            - name: DAGSTER_PG_DB
              valueFrom:
                secretKeyRef:
                  name: dagster-pgsql-config
                  key: PGSQL_DATABASE
            - name: DAGSTER_K8S_PIPELINE_RUN_NAMESPACE
              value: media-prod
          - name: dagster-daemon
            env:
            - name: DAGSTER_PG_USERNAME
              valueFrom:
                secretKeyRef:
                  name: dagster-pgsql-config
                  key: PGSQL_USER
            - name: DAGSTER_PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dagster-pgsql-config
                  key: PGSQL_PASSWORD
            - name: DAGSTER_PG_HOST
              valueFrom:
                secretKeyRef:
                  name: dagster-pgsql-config
                  key: PGSQL_HOST
            - name: DAGSTER_PG_PORT
              valueFrom:
                secretKeyRef:
                  name: dagster-pgsql-config
                  key: PGSQL_PORT
            - name: DAGSTER_PG_DB
              valueFrom:
                secretKeyRef:
                  name: dagster-pgsql-config
                  key: PGSQL_DATABASE
            - name: DAGSTER_K8S_PIPELINE_RUN_NAMESPACE
              value: media-prod
          - name: git-sync
            env:
            - name: GITSYNC_REF
              value: "main"
          initContainers:
          - name: git-sync-init
            env:
            - name: GITSYNC_REF
              value: "main"
          volumes:
          - name: dagster-home
            hostPath:
              path: /d/k8s/volumes/dagster/prod/home
              type: DirectoryOrCreate
          - name: dagster-workspace
            hostPath:
              path: /d/k8s/volumes/dagster/prod/workspace
              type: DirectoryOrCreate

# Dagster Service Patch
- target:
    version: v1
    kind: Service
    name: dagster
  patch: |-
    - op: replace
      path: /spec/ports/0/nodePort
      value: 30300