apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ollama-ingress
spec:
  ingressClassName: traefik
  rules:
    - host: ollama.x81
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: local-llm
                port:
                  number: 11434
