# center-console/overlays/prod/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: media-prod
nameSuffix: -prod
commonLabels:
  variant: prod
patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: center-console
    spec:
      template:
        spec:
          containers:
          - name: center-console
            image: ghcr.io/x81k25/center-console:main
- target:
    version: v1
    kind: Service
    name: center-console
  patch: |-
    - op: replace
      path: /spec/ports/0/nodePort
      value: 30853
- target:
    version: v1
    kind: ConfigMap
    name: center-console-config
  patch: |-
    - op: replace
      path: /data/CENTER_CONSOLE_PORT_EXTERNAL
      value: "30853"