apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media-prod
nameSuffix: -prod

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: center-console
    patch: |-
      - op: replace
        path: /spec/template/metadata/labels/variant
        value: prod
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: ghcr.io/x81k25/center-console:main
  - target:
      kind: Service
      name: center-console
    patch: |-
      - op: replace
        path: /spec/ports/0/nodePort
        value: 30850