apiVersion: apps/v1
kind: Deployment
metadata:
  name: center-console
spec:
  template:
    metadata:
      labels:
        variant: prod
    spec:
      containers:
      - name: center-console
        image: ghcr.io/x81k25/center-console:main
---
apiVersion: v1
kind: Service
metadata:
  name: center-console
spec:
  ports:
  - port: 8501
    targetPort: 8501
    nodePort: 30850