# orchestration app
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-from-git
  namespace: argocd
spec:
  generators:
  # Generator for detecting and using overlay environments
  - git:
      repoURL: https://github.com/x81k25/k8s-manifests
      revision: HEAD
      directories:
      - path: "*-app/overlays/*"  # This matches patterns like atd-app/overlays/dev
  # Generator for apps without overlays (keep your existing pattern)
  - git:
      repoURL: https://github.com/x81k25/k8s-manifests
      revision: HEAD
      directories:
      - path: "*-app"
      - exclude: true
        path: "*-app/overlays"
      - exclude: true 
        path: "*-app/base"
  template:
    metadata:
      name: '{{path.basename}}-{{path.segments.2}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/x81k25/k8s-manifests
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      imagePullSecrets:
      - name: ghcr-pull-image-token