# orchestration app
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-from-git
  namespace: argocd
spec:
  generators:
  # Generator for apps with overlays
  - git:
      repoURL: https://github.com/x81k25/k8s-manifests
      revision: HEAD
      directories:
      - path: "*-app/overlays/*"
  # Generator for regular apps without overlays
  - git:
      repoURL: https://github.com/x81k25/k8s-manifests
      revision: HEAD
      directories:
      - path: "*-app"
      - exclude: true
        path: "*-app/overlays"
      - exclude: true
        path: "*-app/base"
  template:
    metadata:
      # Use a conditional expression to name applications differently based on path structure
      name: '{{if index .path.segments 2}}{{index .path.segments 0}}-{{index .path.segments 2}}{{else}}{{path.basename}}{{end}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/x81k25/k8s-manifests
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      imagePullSecrets:
      - name: ghcr-pull-image-token