# ./app.yaml
# patch command:
## kubectl apply -f media-prod-appset.yaml
# delete appset
## kubectl delete applicationset media-prod-appset -n argocd

apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: media-prod-appset
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: plex
        path: plex/overlays
      #- name: atd-prod
      #  path: atd/overlays/prod
      #- name: music
      #  path: atd/overlays/music
      - name: vpn-gateway
        path: vpn-gateway/overlays
  template:
    metadata:
      name: '{{name}}-prod'
    spec:
      project: default
      source:
        repoURL: https://github.com/x81k25/k8s-manifests.git
        targetRevision: HEAD
        path: "{{path}}/prod"
      destination:
        server: https://kubernetes.default.svc
        namespace: "media-prod"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
 