# ./pgsql-appset.yaml
# patch command:
## kubectl apply -f pgsql-appset.yaml
# verify patch command:
## kubectl get applicationset pgsql-appset -n argocd -o yaml
# delete appset
## kubectl delete applicationset pgsql-appset -n argocd

apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pgsql-appset
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: pgsql-dev
        environment: dev
      - name: pgsql-stg
        environment: stg
      - name: pgsql-prod
        environment: prod
  template:
    metadata:
      name: 'pgsql-{{environment:}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/x81k25/k8s-manifests.git
        targetRevision: HEAD
        path: "pgsql/overlays/{{environment:}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "pgsql"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true