# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: atd-stg
  namespace: automatic-transmission
spec:
  type: NodePort
  ports:
  - port: 9092
    targetPort: 9091
    nodePort: 30092
  selector:
    app: atd-stg