# overlays/dev/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namePrefix: dev-
patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: postgres
  spec:
    template:
      spec:
        containers:
        - name: postgres
          env:
          - name: POSTGRES_USER
            value: postgres-dev
          - name: POSTGRES_PASSWORD
            value: dev-password
          - name: POSTGRES_DB
            value: devdb
        volumes:
        - name: postgres-data
          hostPath:
            path: /mnt/data/postgres-dev