# pgsql/overlays/dev/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namePrefix: dev-
patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: postgres
      namespace: pgsql
    spec:
      template:
        spec:
          containers:
          - name: postgres
            env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: pgsql-dev-config
                  key: pgsql_dev_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgsql-dev-config
                  key: pgsql_dev_password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: pgsql-dev-config
                  key: pgsql_dev_database
          volumes:
          - name: postgres-data
            hostPath:
              path: /d/postgres/dev
  target:
    kind: Deployment
    name: postgres
    namespace: pgsql