apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: wst-flyway-stg-

patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: wst-flyway
      namespace: pgsql
    spec:
      template:
        metadata:
          labels:
            environment: stg
        spec:
          initContainers:
          - name: wst-flyway-migrate
            image: ghcr.io/x81k25/wst-flyway:stg
            env:
            - name: FLYWAY_PGSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: flyway-config-stg
                  key: FLYWAY_PGSQL_HOST
            - name: FLYWAY_PGSQL_PORT
              valueFrom:
                configMapKeyRef:
                  name: flyway-config-stg
                  key: FLYWAY_PGSQL_PORT
            - name: FLYWAY_PGSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: flyway-config-stg
                  key: FLYWAY_PGSQL_DATABASE
            - name: FLYWAY_USER
              valueFrom:
                secretKeyRef:
                  name: flyway-secrets-stg
                  key: FLYWAY_PGSQL_USERNAME
            - name: FLYWAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: flyway-secrets-stg
                  key: FLYWAY_PGSQL_PASSWORD
          containers:
          - name: wst-flyway-main
            image: ghcr.io/x81k25/wst-flyway:stg
  target:
    kind: Deployment
    name: wst-flyway

commonLabels:
  environment: stg