apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

nameSuffix: -stg

patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: wst-flyway
      namespace: pgsql
    spec:
      template:
        metadata:
          labels:
            environment: stg
        spec:
          initContainers:
          - name: wst-flyway-migrate
            image: ghcr.io/x81k25/wst-flyway:stg
            envFrom:
            - configMapRef:
                name: flyway-config-stg
            - secretRef:
                name: flyway-secrets-stg
          containers:
          - name: wst-flyway-main
            image: ghcr.io/x81k25/wst-flyway:stg
  target:
    kind: Deployment
    name: wst-flyway

commonLabels:
  environment: stg