# mlflow/overlays/dev/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
nameSuffix: -dev
commonLabels:
  variant: dev
  environment: dev

patches:
# MLflow Deployment Patch
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: mlflow
    spec:
      template:
        spec:
          containers:
          - name: mlflow
            env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mlflow-dev-secret
                  key: mlflow_dev_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mlflow-dev-secret
                  key: mlflow_dev_password
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: mlflow-dev-secret
                  key: mlflow_dev_name
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: mlflow-dev-secret
                  key: mlflow_dev_port
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mlflow-dev-secret
                  key: mlflow_dev_database
          volumes:
          - name: logs
            hostPath:
              path: /d/k8s/volumes/mlflow/dev/logs
          - name: python-packages
            hostPath:
              path: /d/k8s/volumes/mlflow/dev/packages
              type: DirectoryOrCreate

# MinIO Deployment Patch
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: minio
    spec:
      template:
        spec:
          volumes:
          - name: minio-data
            hostPath:
              path: /d/k8s/volumes/mlflow/dev/minio

# MLflow Service Patch
- target:
    version: v1
    kind: Service
    name: mlflow
  patch: |-
    - op: replace
      path: /spec/ports/0/nodePort
      value: 30501

# MinIO Service Patch
- target:
    version: v1
    kind: Service
    name: minio
  patch: |-
    - op: replace
      path: /spec/ports/0/nodePort
      value: 30911
    - op: replace
      path: /spec/ports/1/nodePort
      value: 30912