apiVersion: v1
kind: Service
metadata:
  name: cici-ears
  namespace: ai-ml
  labels:
    app: cici-ears
spec:
  type: NodePort
  ports:
  - port: 8766
    targetPort: 8766
    nodePort: 30212
    name: websocket
  - port: 9766
    targetPort: 9766
    nodePort: 30214
    name: metrics
  selector:
    app: cici-ears
