apiVersion: v1
kind: Service
metadata:
  name: cici-ears
  namespace: ai-ml
  labels:
    app: cici-ears
spec:
  type: NodePort
  ports:
  - port: 8766
    targetPort: 8766
    nodePort: 30212
  selector:
    app: cici-ears
