apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  namespace: media-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      hostNetwork: true
      containers:
        - name: plex
          image: plexinc/pms-docker:latest
          env:
            - name: TZ
              value: "America/Chicago"
            - name: PLEX_CLAIM
              valueFrom:
                secretKeyRef:
                  name: plex-config
                  key: PLEX_CLAIM
            - name: ADVERTISE_IP
              value: "http://server-ip:32400/"
          volumeMounts:
            - mountPath: /config
              name: plex-config
            - mountPath: /transcode
              name: plex-transcode
            - mountPath: /data
              name: plex-media
      volumes:
        - name: plex-config
          hostPath:
            path: /d/k8s/volumes/plex/config
        - name: plex-transcode
          hostPath:
            path: /d/k8s/volumes/plex/transcode
        - name: plex-media
          hostPath:
            path: /k/media