apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  namespace: media-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      hostNetwork: true
      containers:
        - name: plex
          image: linuxserver/plex:1.32.8
          env:
            - name: PUID
              value: "999"
            - name: PGID
              value: "999"
            - name: TZ
              value: "America/Chicago"
            - name: PLEX_CLAIM
              valueFrom:
                secretKeyRef:
                  name: plex-config
                  key: PLEX_CLAIM
            - name: NVIDIA_VISIBLE_DEVICES
              value: "all"
          ports:
            - containerPort: 32400
              name: web
            - containerPort: 1900
              protocol: UDP
              name: dlna
            - containerPort: 3005
              name: control
            - containerPort: 8324
              name: control-alt
            - containerPort: 32469
              name: streaming
            - containerPort: 32410
              protocol: UDP
              name: gdm-1
            - containerPort: 32412
              protocol: UDP
              name: gdm-2
            - containerPort: 32413
              protocol: UDP
              name: gdm-3
            - containerPort: 32414
              protocol: UDP
              name: gdm-4
          volumeMounts:
            - mountPath: /config
              name: plex-config
            - mountPath: /data
              name: plex-data
            - mountPath: /transcode
              name: plex-transcode
            - mountPath: /media
              name: plex-media
          securityContext:
            runAsUser: 999
            runAsGroup: 999
#            supplementalGroups:
#              - 44 
#              - 1001  
          livenessProbe:
            httpGet:
              path: /web/index.html
              port: 32400
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /web/index.html
              port: 32400
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            limits:
              nvidia.com/gpu: "1"
      volumes:
        - name: plex-config
          hostPath:
            path: /d/k8s/volumes/plex/config
            type: Directory
        - name: plex-data
          hostPath:
            path: /d/k8s/volumes/plex/data
            type: Directory
        - name: plex-transcode
          hostPath:
            path: /d/k8s/volumes/plex/transcode
            type: Directory
        - name: plex-media
          hostPath:
            path: /k/media
            type: Directory