# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: plex
  namespace: media-prod
spec:
  type: ClusterIP
  ports:
    - port: 32400
      targetPort: 32400
      protocol: TCP
      name: web
    - port: 1900
      targetPort: 1900
      protocol: UDP
      name: dlna
    - port: 3005
      targetPort: 3005
      protocol: TCP
      name: control
    - port: 8324
      targetPort: 8324
      protocol: TCP
      name: control-alt
    - port: 32469
      targetPort: 32469
      protocol: TCP
      name: streaming
    - port: 32410
      targetPort: 32410
      protocol: UDP
      name: gdm-1
    - port: 32412
      targetPort: 32412
      protocol: UDP
      name: gdm-2
    - port: 32413
      targetPort: 32413
      protocol: UDP
      name: gdm-3
    - port: 32414
      targetPort: 32414
      protocol: UDP
      name: gdm-4
  selector:
    app: plex