# overlays/prod/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namePrefix: prod-
patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: postgres
      namespace: pgsql
    spec:
      template:
        spec:
          containers:
          - name: postgres
            env:
            - name: POSTGRES_USER
              value: postgres-prod
            - name: POSTGRES_PASSWORD
              value: prod-password
            - name: POSTGRES_DB
              value: proddb
          volumes:
          - name: postgres-data
            hostPath:
              path: /mnt/data/postgres-prod
  target:
    kind: Deployment
    name: postgres
    namespace: pgsql