# pgsql/overlays/prod/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namePrefix: prod-
patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: postgres
      namespace: pgsql
    spec:
      template:
        spec:
          containers:
          - name: postgres
            env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: pgsql-prod-config
                  key: pgsql_prod_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgsql-prod-config
                  key: pgsql_prod_password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: pgsql-prod-config
                  key: pgsql_prod_database
            - name: PG_MOUNT_PATH
              valueFrom:
                secretKeyRef:
                  name: pgsql-prod-config
                  key: pgsql_prod_mount
          volumes:
          - name: postgres-data
            hostPath:
              path: $(PG_MOUNT_PATH)
  target:
    kind: Deployment
    name: postgres
    namespace: pgsql