# pgsql/overlays/prod/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namePrefix: prod-
patches:
- patch: |-
    apiVersion: apps/v1
    kind: StatefulSet
    metadata:
      name: postgres
      namespace: pgsql
    spec:
      template:
        metadata:
          labels:
            app: postgres
            environment: prod
        spec:
          containers:
          - name: postgres
            env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: pgsql-prod-config
                  key: pgsql_prod_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgsql-prod-config
                  key: pgsql_prod_password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: pgsql-prod-config
                  key: pgsql_prod_database
          volumes:
          - name: postgres-data
            hostPath:
              path: /d/postgres/prod
  target:
    kind: StatefulSet
    name: postgres
    namespace: pgsql
- patch: |-
    apiVersion: v1
    kind: Service
    metadata:
      name: postgres
      namespace: pgsql
    spec:
      $patch: replace
      type: NodePort
      ports:
      - port: 5432
        targetPort: 5432
        nodePort: 31432
        name: postgres
        protocol: TCP
      selector:
        app: postgres
        environment: prod
  target:
    kind: Service
    name: postgres
    namespace: pgsql