apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
nameSuffix: -prod
commonLabels:
  variant: prod
namespace: media-prod
patches:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: vpn-gateway
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: ghcr.io/x81k25/vpn-gateway:main
- target:
    version: v1
    kind: Service
    name: vpn-gateway
  patch: |-
    - op: replace
      path: /spec/ports/1/port
      value: 8120