apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin4-servers-json
  namespace: pgsql
  labels:
    app: pgadmin4
    managed-by: argocd
data:
  servers.json: |
    {
      "Servers": {
        "1": {
          "Name": "PostgreSQL-DEV",
          "Group": "Development",
          "Host": "dev-pgsql.pgsql.svc.cluster.local",
          "Port": 5434,
          "MaintenanceDB": "postgres",
          "Username": "postgres",
          "SSLMode": "prefer",
          "PassFile": "/pgpassfile-dev"
        },
        "2": {
          "Name": "PostgreSQL-STG",
          "Group": "Staging",
          "Host": "stg-pgsql.pgsql.svc.cluster.local",
          "Port": 5433,
          "MaintenanceDB": "postgres",
          "Username": "postgres",
          "SSLMode": "prefer",
          "PassFile": "/pgpassfile-stg"
        },
        "3": {
          "Name": "PostgreSQL-PROD",
          "Group": "Production",
          "Host": "prod-pgsql.pgsql.svc.cluster.local",
          "Port": 5432,
          "MaintenanceDB": "postgres",
          "Username": "postgres",
          "SSLMode": "prefer",
          "PassFile": "/pgpassfile-prod"
        }
      }
    }