apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: pgsql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
      - name: pgadmin
        image: dpage/pgadmin4:latest
        ports:
        - containerPort: 80
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          valueFrom:
            secretKeyRef:
              name: pgadmin-credentials
              key: pgadmin_email
        - name: PGADMIN_DEFAULT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pgadmin-credentials
              key: pgadmin_password
        - name: PGADMIN_MOUNT_PATH
          valueFrom:
            secretKeyRef:
              name: pgadmin-credentials
              key: pgadmin_mount
        volumeMounts:
        - name: pgadmin-data
          mountPath: $(PGADMIN_MOUNT_PATH)
      volumes:
      - name: pgadmin-data
        persistentVolumeClaim:
          claimName: pgadmin-data