apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin4
  namespace: pgsql
  labels:
    app: pgadmin4
    managed-by: terraform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin4
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pgadmin4
    spec:
      securityContext:
        fsGroup: 999
        runAsUser: 5050
        runAsGroup: 5050
      containers:
      - name: pgadmin4
        image: dpage/pgadmin4:latest
        ports:
        - containerPort: 80
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          valueFrom:
            secretKeyRef:
              name: pgadmin4-secrets
              key: email
        - name: PGADMIN_DEFAULT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pgadmin4-secrets
              key: password
        - name: PGADMIN_LISTEN_PORT
          valueFrom:
            secretKeyRef:
              name: pgadmin4-secrets
              key: listen_port
        - name: PGADMIN_LISTEN_ADDRESS
          valueFrom:
            secretKeyRef:
              name: pgadmin4-secrets
              key: listen_address
        - name: PGADMIN_SERVER_MODE
          valueFrom:
            secretKeyRef:
              name: pgadmin4-secrets
              key: server_mode
        - name: PGADMIN_SERVER_JSON_FILE
          value: "/pgadmin4/servers.json"
        volumeMounts:
        - name: pgadmin4-data
          mountPath: /var/lib/pgadmin
        - name: pgadmin4-servers
          mountPath: /pgadmin4
      volumes:
      - name: pgadmin4-data
        hostPath:
          path: "/mnt/data/pgadmin"
          type: DirectoryOrCreate
      - name: pgadmin4-servers
        secret:
          secretName: pgadmin4-servers-secret