# File: deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin4
  namespace: pgsql
  labels:
    app: pgadmin4
    managed-by: terraform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin4
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pgadmin4
    spec:
      securityContext:
        fsGroup: ${{pgadmin4_config.fs_grounp}}
        runAsUser: ${{pgadmin4_config.UID}}
        runAsGroup: ${{pgadmin4_config.GID}}
      containers:
      - name: pgadmin4
        image: dpage/pgadmin4:latest
        ports:
        - containerPort: ${{pgadmin4_config.listen_port}}
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: "${pgadmin4_config.email}"
        - name: PGADMIN_DEFAULT_PASSWORD
          value: "${pgadmin4_config.password}"
        - name: PGADMIN_LISTEN_PORT
          value: "${{pgadmin4_config.listen_port}}"
        - name: PGADMIN_LISTEN_ADDRESS
          value: "${pgadmin4_config.listen_address}"
        - name: PGADMIN_SERVER_MODE
          value: "${pgadmin4_config.server_mode}"
        - name: PGADMIN_SERVER_JSON_FILE
          value: "/pgadmin4/servers.json"
        volumeMounts:
        - name: pgadmin4-data
          mountPath: /var/lib/pgadmin
        - name: pgadmin4-servers
          mountPath: /pgadmin4
      volumes:
      - name: pgadmin4-data
        hostPath:
          path: "${pgadmin4_config.mount}"
          type: DirectoryOrCreate
      - name: pgadmin4-servers
        configMap:
          name: pgadmin4-servers