apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin4
  namespace: pgsql
  labels:
    app: pgadmin4
    managed-by: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin4
  template:
    metadata:
      labels:
        app: pgadmin4
    spec:
      securityContext:
        fsGroup: 1001
      containers:
        - name: pgadmin4
          image: dpage/pgadmin4:8.8
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: pgadmin4-secrets
                  key: pgadmin4_email
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgadmin4-secrets
                  key: pgadmin4_password
            - name: PGADMIN_LISTEN_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: pgadmin4-config
                  key: pgadmin4_listen_address
            - name: PGADMIN_LISTEN_PORT
              valueFrom:
                configMapKeyRef:
                  name: pgadmin4-config
                  key: pgadmin4_listen_port
            - name: PGADMIN_SERVER_JSON_FILE
              value: /pgadmin4/servers.json
          volumeMounts:
            - name: pgadmin-data
              mountPath: /var/lib/pgadmin
            - name: servers-json
              mountPath: /pgadmin4/servers.json
              subPath: servers.json
          securityContext:
            runAsUser: 1000
            runAsGroup: 1001
      volumes:
        - name: pgadmin-data
          hostPath:
            path: /data/pgadmin
        - name: servers-json
          configMap:
            name: pgadmin4-servers-json