apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin4
  namespace: pgsql
  labels:
    app: pgadmin4
    managed-by: terraform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin4
  template:
    metadata:
      labels:
        app: pgadmin4
    spec:
      securityContext:
        fsGroup: ${pgadmin4_config.fs_grounp}
      containers:
        - name: pgadmin4
          image: dpage/pgadmin4:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: ${pgadmin4_config.listen_port}
              name: pgadmin4
          securityContext:
            runAsUser: ${pgadmin4_config.UID}
            runAsGroup: ${pgadmin4_config.GID}
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: pgadmin4-secrets
                  key: email
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgadmin4-secrets
                  key: password
            - name: PGADMIN_LISTEN_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: pgadmin4-secrets
                  key: listen_address
            - name: PGADMIN_LISTEN_PORT
              valueFrom:
                secretKeyRef:
                  name: pgadmin4-secrets
                  key: listen_port
            - name: PGADMIN_SERVER_MODE
              valueFrom:
                secretKeyRef:
                  name: pgadmin4-secrets
                  key: server_mode
            - name: SERVER_IP
              valueFrom:
                configMapKeyRef:
                  name: server-ip-config
                  key: SERVER_IP
          volumeMounts:
            - name: pgadmin4-data
              mountPath: ${pgadmin4_config.mount}
            - name: servers-json
              mountPath: /pgadmin4/servers.json
              subPath: servers.json
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /misc/ping
              port: pgadmin4
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /misc/ping
              port: pgadmin4
            initialDelaySeconds: 10
            periodSeconds: 5
      volumes:
        - name: pgadmin4-data
          hostPath:
            path: ${pgadmin4_config.mount}
        - name: servers-json
          secret:
            secretName: pgadmin4-servers-secret