# pgadmin4/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- servers-configmap.yaml
- env-configmap.yaml
- ingress.yaml

vars:
  - name: UID
    objref:
      kind: ConfigMap
      name: pgadmin4-vars
      apiVersion: v1
    fieldref:
      fieldpath: data.uid
  - name: GID
    objref:
      kind: ConfigMap
      name: pgadmin4-vars
      apiVersion: v1
    fieldref:
      fieldpath: data.gid
  - name: FS_GROUP
    objref:
      kind: ConfigMap
      name: pgadmin4-vars
      apiVersion: v1
    fieldref:
      fieldpath: data.fs_group
  - name: MOUNT
    objref:
      kind: ConfigMap
      name: pgadmin4-vars
      apiVersion: v1
    fieldref:
      fieldpath: data.mount
  - name: PORT
    objref:
      kind: ConfigMap
      name: pgadmin4-vars
      apiVersion: v1
    fieldref:
      fieldpath: data.port
  - name: LISTEN_PORT
    objref:
      kind: ConfigMap
      name: pgadmin4-vars
      apiVersion: v1
    fieldref:
      fieldpath: data.listen_port
  - name: SERVER_IP
    objref:
      kind: ConfigMap
      name: pgadmin4-vars
      apiVersion: v1
    fieldref:
      fieldpath: data.server_ip

configMapGenerator:
- name: pgadmin4-vars
  literals:
  - uid=${pgadmin4_config.UID}
  - gid=${pgadmin4_config.GID}
  - fs_group=${pgadmin4_config.fs_grounp}
  - mount=${pgadmin4_config.mount}
  - port=${pgadmin4_config.port}
  - listen_port=${pgadmin4_config.listen_port}
  - server_ip=${server_ip}