apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- ingress.yaml

# Reference the ConfigMap that Terraform created
vars:
- name: SERVER_IP
  objref:
    kind: ConfigMap
    name: server-ip-config
    apiVersion: v1
  fieldref:
    fieldpath: data.SERVER_IP