apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- ingress.yaml

# We'll use a ConfigMap to store the server IP for Kustomize replacement
configMapGenerator:
- name: server-ip-config
  literals:
  - server_ip=PLACEHOLDER_IP

# Replace the placeholder in the ingress host
patches:
- target:
    kind: Ingress
    name: pgadmin4
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: pgadmin.$(server-ip-config.server_ip).nip.io