apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- ingress.yaml

# Use replacements instead of vars
replacements:
- source:
    kind: ConfigMap
    name: server-ip-config
    fieldPath: data.SERVER_IP
  targets:
  - select:
      kind: Ingress
      name: pgadmin4
    fieldPaths:
    - spec.rules.0.host
    options:
      create: true
      delimiter: .
      index: 1