apiVersion: v1
kind: Service
metadata:
  name: pgadmin4
  namespace: pgsql
  labels:
    app: pgadmin4
    managed-by: terraform
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: pgadmin4
  type: ClusterIP