apiVersion: v1
kind: Service
metadata:
  name: pgadmin4
  namespace: pgsql
  labels:
    app: pgadmin4
    managed-by: terraform
spec:
  type: ClusterIP
  ports:
    - port: ${pgadmin4_config.port}
      targetPort: pgadmin4
      protocol: TCP
      name: http
  selector:
    app: pgadmin4