# dagster/overlays/dev/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media-dev
resources:
- ../../base
- deployment.yaml

# Exclude base deployment to use our custom one
patches:
- target:
    kind: Deployment
    name: dagster
  patch: |-
    $patch: delete
nameSuffix: -dev
commonLabels:
  variant: dev
  environment: dev

# Dagster Service Patch
patches:
- target:
    version: v1
    kind: Service
    name: dagster
  patch: |-
    - op: replace
      path: /spec/ports/0/nodePort
      value: 30302