# dagster/overlays/dev/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media-dev
resources:
- ../../base
nameSuffix: -dev
commonLabels:
  variant: dev
  environment: dev

patches:
# Dagster Deployment Patch
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: dagster
    spec:
      template:
        spec:
          containers:
          - name: dagster-dagit
            env:
            - name: DAGSTER_PG_USERNAME
              valueFrom:
                secretKeyRef:
                  name: dagster-pgsql-config
                  key: PGSQL_USER
            - name: DAGSTER_PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dagster-pgsql-config
                  key: PGSQL_PASSWORD
            - name: DAGSTER_PG_HOST
              valueFrom:
                secretKeyRef:
                  name: dagster-pgsql-config
                  key: PGSQL_HOST
            - name: DAGSTER_PG_PORT
              valueFrom:
                secretKeyRef:
                  name: dagster-pgsql-config
                  key: PGSQL_PORT
            - name: DAGSTER_PG_DB
              valueFrom:
                secretKeyRef:
                  name: dagster-pgsql-config
                  key: PGSQL_DATABASE
            - name: DAGSTER_K8S_PIPELINE_RUN_NAMESPACE
              value: media-dev
            command:
            - bash
            - -c
            - |
              mkdir -p $DAGSTER_HOME
              cat > $DAGSTER_HOME/dagster.yaml << EOL
              run_storage:
                module: dagster_postgres.run_storage
                class: PostgresRunStorage
                config:
                  postgres_db:
                    username: ${DAGSTER_PG_USERNAME}
                    password: ${DAGSTER_PG_PASSWORD}
                    hostname: ${DAGSTER_PG_HOST}
                    port: ${DAGSTER_PG_PORT}
                    db_name: ${DAGSTER_PG_DB}
                    
              schedule_storage:
                module: dagster_postgres.schedule_storage
                class: PostgresScheduleStorage
                config:
                  postgres_db:
                    username: ${DAGSTER_PG_USERNAME}
                    password: ${DAGSTER_PG_PASSWORD}
                    hostname: ${DAGSTER_PG_HOST}
                    port: ${DAGSTER_PG_PORT}
                    db_name: ${DAGSTER_PG_DB}
                    
              event_log_storage:
                module: dagster_postgres.event_log
                class: PostgresEventLogStorage
                config:
                  postgres_db:
                    username: ${DAGSTER_PG_USERNAME}
                    password: ${DAGSTER_PG_PASSWORD}
                    hostname: ${DAGSTER_PG_HOST}
                    port: ${DAGSTER_PG_PORT}
                    db_name: ${DAGSTER_PG_DB}
                    
              run_coordinator:
                module: dagster.core.run_coordinator
                class: DefaultRunCoordinator
                  
              run_launcher:
                module: dagster.core.launcher
                class: DefaultRunLauncher
              EOL
              
              cat > $DAGSTER_HOME/workspace.yaml << EOL
              load_from:
                - git:
                    url: "https://github.com/x81k25/dagstributor"
                    branch: "dev"
                    executable_path: "dagster"
              EOL
              
              dagster-webserver -h 0.0.0.0 -p 3000 -w $DAGSTER_HOME/workspace.yaml
          - name: dagster-daemon
            env:
            - name: DAGSTER_PG_USERNAME
              valueFrom:
                secretKeyRef:
                  name: dagster-pgsql-config
                  key: PGSQL_USER
            - name: DAGSTER_PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dagster-pgsql-config
                  key: PGSQL_PASSWORD
            - name: DAGSTER_PG_HOST
              valueFrom:
                secretKeyRef:
                  name: dagster-pgsql-config
                  key: PGSQL_HOST
            - name: DAGSTER_PG_PORT
              valueFrom:
                secretKeyRef:
                  name: dagster-pgsql-config
                  key: PGSQL_PORT
            - name: DAGSTER_PG_DB
              valueFrom:
                secretKeyRef:
                  name: dagster-pgsql-config
                  key: PGSQL_DATABASE
            - name: DAGSTER_K8S_PIPELINE_RUN_NAMESPACE
              value: media-dev
          volumes:
          - name: dagster-home
            hostPath:
              path: /d/k8s/volumes/dagster/dev/home
              type: DirectoryOrCreate
          - name: dagster-workspace
            hostPath:
              path: /d/k8s/volumes/dagster/dev/workspace
              type: DirectoryOrCreate

# Dagster Service Patch
- target:
    version: v1
    kind: Service
    name: dagster
  patch: |-
    - op: replace
      path: /spec/ports/0/nodePort
      value: 30302