# dagster/overlays/dev/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media-dev
resources:
- ../../base/service.yaml
- ../../base/configmap.yaml
- ../../base/rbac.yaml
- deployment.yaml
nameSuffix: -dev
commonLabels:
  variant: dev
  environment: dev

# Dagster Service Patch
patches:
- target:
    version: v1
    kind: Service
    name: dagster
  patch: |-
    - op: replace
      path: /spec/ports/0/nodePort
      value: 30302