# dagster/overlays/dev/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media-dev
resources:
- ../../base/configmap.yaml
- ../../base/rbac.yaml
- deployment.yaml
- service.yaml
nameSuffix: -dev
commonLabels:
  variant: dev
  environment: dev