# dagster/overlays/dev/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media-dev
resources:
- ../../base
nameSuffix: -dev
commonLabels:
  variant: dev
  environment: dev

patches:
# Dagster Deployment Patch
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: dagster
    spec:
      template:
        spec:
          containers:
          - name: dagster-dagit
            envFrom:
            - configMapRef:
                name: environment
            - configMapRef:
                name: wst-config
            - secretRef:
                name: wst-secrets
            - configMapRef:
                name: dagster-config
            - secretRef:
                name: dagster-secrets
            - configMapRef:
                name: rear-diff-config
            - secretRef:
                name: rear-diff-secrets
            - configMapRef:
                name: reel-driver-config
            - configMapRef:
                name: at-config
            - secretRef:
                name: at-secrets
            - configMapRef:
                name: transmission-config
            - secretRef:
                name: transmission-secrets
            env:
            - name: DAGSTER_K8S_PIPELINE_RUN_NAMESPACE
              value: media-dev
          - name: dagster-daemon
            envFrom:
            - configMapRef:
                name: environment
            - configMapRef:
                name: wst-config
            - secretRef:
                name: wst-secrets
            - configMapRef:
                name: dagster-config
            - secretRef:
                name: dagster-secrets
            - configMapRef:
                name: rear-diff-config
            - secretRef:
                name: rear-diff-secrets
            - configMapRef:
                name: reel-driver-config
            - configMapRef:
                name: at-config
            - secretRef:
                name: at-secrets
            - configMapRef:
                name: transmission-config
            - secretRef:
                name: transmission-secrets
            env:
            - name: DAGSTER_K8S_PIPELINE_RUN_NAMESPACE
              value: media-dev
          - name: git-sync
            env:
            - name: GITSYNC_REF
              value: "dev"
          initContainers:
          - name: git-sync-init
            env:
            - name: GITSYNC_REF
              value: "dev"
          volumes:
          - name: dagster-home
            hostPath:
              path: /d/k8s/volumes/dagster/dev/home
              type: DirectoryOrCreate
          - name: dagster-workspace
            hostPath:
              path: /d/k8s/volumes/dagster/dev/workspace
              type: DirectoryOrCreate

# Dagster Service Patch
- target:
    version: v1
    kind: Service
    name: dagster
  patch: |-
    - op: replace
      path: /spec/ports/0/nodePort
      value: 30302