# dagster/overlays/dev/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: dagster
  labels:
    app: dagster
spec:
  type: NodePort
  selector:
    app: dagster
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30302
    name: dagit-http