# dagster/overlays/dev/volume-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: dagster-volume-paths
  labels:
    app: dagster
    environment: dev
data:
  DAGSTER_HOME_VOLUME_PATH: "/d/k8s/volumes/dagster/dev/home"
  DAGSTER_WORKSPACE_VOLUME_PATH: "/d/k8s/volumes/dagster/dev/workspace"