# mlflow/overlays/stg/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: pgsql
nameSuffix: -stg
commonLabels:
  variant: stg
  environment: stg

patches:
# MLflow Deployment Patch
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: mlflow
    spec:
      template:
        spec:
          containers:
          - name: mlflow
            env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mlflow-stg-secret
                  key: mlflow_stg_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mlflow-stg-secret
                  key: mlflow_stg_password
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: mlflow-stg-secret
                  key: mlflow_stg_name
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: mlflow-stg-secret
                  key: mlflow_stg_port
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mlflow-stg-secret
                  key: mlflow_stg_database
          volumes:
          - name: logs
            hostPath:
              path: /d/k8s/volumes/mlflow/stg/logs
              type: DirectoryOrCreate
          - name: python-packages
            hostPath:
              path: /d/k8s/volumes/mlflow/stg/packages
              type: DirectoryOrCreate
          - name: artifacts
            hostPath:
              path: /d/k8s/volumes/mlflow/stg/artifacts
              type: DirectoryOrCreate

# MLflow Service Patch
- target:
    version: v1
    kind: Service
    name: mlflow
  patch: |-
    - op: replace
      path: /spec/ports/0/nodePort
      value: 30501