apiVersion: v1
kind: ConfigMap
metadata:
  name: vpn-gateway-config
  namespace: media-dev
data:
  setup.sh: |
    #!/bin/sh
    iptables -t nat -A POSTROUTING -o tun0 -j MASQUERADE
    iptables -A FORWARD -i eth0 -o tun0 -j ACCEPT
    iptables -A FORWARD -i tun0 -o eth0 -j ACCEPT
    echo 1 > /proc/sys/net/ipv4/ip_forward
    
    # Install and configure Privoxy if not already installed
    if ! command -v privoxy &> /dev/null; then
      apt-get update && apt-get install -y privoxy
    fi
    
    # Configure privoxy to accept more connections
    sed -i 's/listen-address.*/listen-address 0.0.0.0:8118/' /etc/privoxy/config
    sed -i 's/max-client-connections.*/max-client-connections 256/' /etc/privoxy/config
    
    # Start Privoxy
    privoxy --no-daemon /etc/privoxy/config &
    
    # Run the VPN client
    exec "$@"
  config: |
    listen-address 0.0.0.0:8118
    max-client-connections 512
    toggle 1
    enable-remote-toggle 0
    enable-remote-http-toggle 0
    enable-edit-actions 0
    debug 1
    # Use direct connection instead of SOCKS
    forward / .
    forwarded-connect-retries 5