apiVersion: v1
kind: ConfigMap
metadata:
  name: vpn-gateway-config
  namespace: media-dev
data:
  setup.sh: |
    #!/bin/sh
    iptables -t nat -A POSTROUTING -o tun0 -j MASQUERADE
    iptables -A FORWARD -i eth0 -o tun0 -j ACCEPT
    iptables -A FORWARD -i tun0 -o eth0 -j ACCEPT
    echo 1 > /proc/sys/net/ipv4/ip_forward
    # Run the VPN client
    exec "$@"