apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpn-gateway
  namespace: media-dev  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vpn-gateway
  template:
    metadata:
      labels:
        app: vpn-gateway
    spec:
      containers:
      - name: vpn-gateway
        image: ghcr.io/x81k25/vpn-gateway:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
          capabilities:
            add: ["NET_ADMIN"]
        ports:
        - containerPort: 1194
          protocol: UDP
        - containerPort: 8118
          protocol: TCP
        volumeMounts:
        - name: config-volume
          mountPath: /etc/privoxy
        command: ["/bin/sh", "/scripts/setup.sh"]
      volumes:
      - name: config-volume
        configMap:
          name: vpn-gateway-config
      imagePullSecrets:
      - name: ghcr-pull-image-token