apiVersion: v1
kind: Service
metadata:
  name: vpn-gateway
  namespace: media-dev
spec:
  selector:
    app: vpn-gateway
  ports:
  - name: vpn
    port: 1194
    protocol: UDP
    targetPort: 1194
  - name: proxy
    port: 8118
    protocol: TCP
    targetPort: 8118