# ./overlays/prod/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
nameSuffix: -prod
commonLabels:
  variant: prod
patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: plex
    spec:
      template:
        spec:
          hostNetwork: true
          containers:
          - name: plex
            resources:
              limits:
                memory: 2Gi
                cpu: 1000m
            volumeMounts:
            - name: plex-config
              mountPath: /config
            - name: plex-transcode
              mountPath: /transcode
            - name: plex-media
              mountPath: /data
            - name: usb-devices
              mountPath: /dev/bus/usb
          volumes:
          - name: usb-devices
            hostPath:
              path: /dev/bus/usb