{
 "title": "namespace-resources",
 "tags": [
  "kubernetes",
  "namespace",
  "resources"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_created, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CPU (cores)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "current usage vs limits (%)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container!=\"POD\",container!=\"\"}[5m])) / sum(kube_resourcequota{namespace=\"$namespace\",resource=\"requests.cpu\",type=\"hard\"})"
    }
   ]
  },
  {
   "title": "namespace requests quota (cores)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_resourcequota{namespace=\"$namespace\",resource=\"requests.cpu\",type=\"hard\"})"
    }
   ]
  },
  {
   "title": "requests usage vs quota (%)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\",resource=\"cpu\"} * on(namespace,pod) group_left() kube_pod_status_phase{namespace=\"$namespace\",phase=\"Running\"}) / sum(kube_resourcequota{namespace=\"$namespace\",resource=\"requests.cpu\",type=\"hard\"})"
    }
   ]
  },
  {
   "title": "limits usage vs quota (%)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\",resource=\"cpu\"} * on(namespace,pod) group_left() kube_pod_status_phase{namespace=\"$namespace\",phase=\"Running\"}) / sum(kube_resourcequota{namespace=\"$namespace\",resource=\"limits.cpu\",type=\"hard\"})"
    }
   ]
  },
  {
   "title": "namespace limits quota (cores)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_resourcequota{namespace=\"$namespace\",resource=\"limits.cpu\",type=\"hard\"})"
    }
   ]
  },
  {
   "title": "CPU over time (cores)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "usage by container (cores)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container!=\"POD\",container!=\"\"}[5m])) by (container)",
       "legendFormat": "{{container}}"
      },
      {
       "expr": "sum(kube_resourcequota{namespace=\"$namespace\",resource=\"requests.cpu\",type=\"hard\"}) ",
       "legendFormat": "total requests (namespace)"
      },
      {
       "expr": "sum(kube_resourcequota{namespace=\"$namespace\",resource=\"limits.cpu\",type=\"hard\"})",
       "legendFormat": "total limits (namespace)"
      }
     ]
    },
    {
     "title": "requests by container (% of quota)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
     "targets": [
      {
       "expr": "  sum(kube_pod_container_resource_requests{namespace=\"$namespace\",resource=\"cpu\"} * on(namespace,pod) group_left() kube_pod_status_phase{namespace=\"$namespace\",phase=\"Running\"}) by (container) / scalar(sum(kube_resourcequota{namespace=\"$namespace\",resource=\"requests.cpu\",type=\"hard\"})) * 100",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "limits by container (% of quota)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
     "targets": [
      {
       "expr": "  sum(kube_pod_container_resource_limits{namespace=\"$namespace\",resource=\"cpu\"} * on(namespace,pod) group_left() kube_pod_status_phase{namespace=\"$namespace\",phase=\"Running\"}) by (container) / scalar(sum(kube_resourcequota{namespace=\"$namespace\",resource=\"limits.cpu\",type=\"hard\"})) * 100",
       "legendFormat": "{{container}}"
      }
     ]
    }
   ]
  },
  { "title": "RAM (GiB)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "current usage vs limits (%)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",container!=\"POD\",container!=\"\"}) / sum(kube_resourcequota{namespace=\"$namespace\",resource=\"limits.memory\",type=\"hard\"})"
    }
   ]
  },
  {
   "title": "namespace requests quota (GiB)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_resourcequota{namespace=\"$namespace\",resource=\"requests.memory\",type=\"hard\"}/1024/1024/1024)"
    }
   ]
  },
  {
   "title": "requests usage vs quota (%)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\",resource=\"memory\"} * on(namespace,pod) group_left() kube_pod_status_phase{namespace=\"$namespace\",phase=\"Running\"}) / sum(kube_resourcequota{namespace=\"$namespace\",resource=\"requests.memory\",type=\"hard\"})"
    }
   ]
  },
  {
   "title": "limits usage vs quota (%)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\",resource=\"memory\"} * on(namespace,pod) group_left() kube_pod_status_phase{namespace=\"$namespace\",phase=\"Running\"}) / sum(kube_resourcequota{namespace=\"$namespace\",resource=\"limits.memory\",type=\"hard\"})"
    }
   ]
  },
  {
   "title": "namespace limits quota (GiB)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_resourcequota{namespace=\"$namespace\",resource=\"limits.memory\",type=\"hard\"}/1024/1024/1024)"
    }
   ]
  },
  {
   "title": "RAM over time (GiB)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "usage by container (GiB)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",container!=\"POD\",container!=\"\"}) by (container) /1024/1024/1024   ",
       "legendFormat": "{{container}}"
      },
      {
       "expr": "sum(kube_resourcequota{namespace=\"$namespace\",resource=\"requests.memory\",type=\"hard\"}) /1024/1024/1024   ",
       "legendFormat": "total requests (namespace)"
      },
      {
       "expr": "sum(kube_resourcequota{namespace=\"$namespace\",resource=\"limits.memory\",type=\"hard\"}) /1024/1024/1024   ",
       "legendFormat": "total limits (namespace)"
      }
     ]
    },
    {
     "title": "requests by container (% of quota)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 16 },
     "targets": [
      {
       "expr": "  sum(kube_pod_container_resource_requests{namespace=\"$namespace\",resource=\"memory\"} * on(namespace,pod) group_left() kube_pod_status_phase{namespace=\"$namespace\",phase=\"Running\"}) by (container) / scalar(sum(kube_resourcequota{namespace=\"$namespace\",resource=\"requests.memory\",type=\"hard\"})) * 100",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "limits by container (% of quota)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 16 },
     "targets": [
      {
       "expr": "  sum(kube_pod_container_resource_limits{namespace=\"$namespace\",resource=\"memory\"} * on(namespace,pod) group_left() kube_pod_status_phase{namespace=\"$namespace\",phase=\"Running\"}) by (container) / scalar(sum(kube_resourcequota{namespace=\"$namespace\",resource=\"limits.memory\",type=\"hard\"})) * 100",
       "legendFormat": "{{container}}"
      }
     ]
    }
   ]
  },
  { "title": "rtx3060-8a56", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "utilization (%)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(DCGM_FI_DEV_GPU_UTIL{UUID=~\".*8a56.*\", namespace=\"$namespace\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "VRAM (GiB)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(DCGM_FI_DEV_FB_USED{UUID=~\".*8a56.*\", namespace=\"$namespace\"}) / 1024",
     "legendFormat": "total"
    }
   ]
  },
  { "title": "rtx3060-cfbe", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "utilization (%)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(DCGM_FI_DEV_GPU_UTIL{UUID=~\".*cfbe.*\", namespace=\"$namespace\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "VRAM (GiB)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(DCGM_FI_DEV_FB_USED{UUID=~\".*cfbe.*\", namespace=\"$namespace\"}) / 1024",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "GPU over time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU utilization by container (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "label_replace(max by (pod, UUID) (DCGM_FI_DEV_GPU_UTIL{namespace=\"$namespace\"}), \"gpu_short\", \"$1\", \"UUID\", \"GPU-(.{4}).*\")",
       "legendFormat": "rtx3060-{{gpu_short}} - {{pod}}"
      }
     ]
    },
    {
     "title": "VRAM usage by container (GiB)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "label_replace(max by (pod, UUID) (DCGM_FI_DEV_FB_USED{namespace=\"$namespace\"}), \"gpu_short\", \"$1\", \"UUID\", \"GPU-(.{4}).*\") / 1024",
       "legendFormat": "rtx3060-{{gpu_short}} - {{pod}}"
      }
     ]
    }
   ]
  },
  { "title": "container resource summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "container resource summary",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container!=\"POD\",container!=\"\"}[5m])) by (container, pod)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",container!=\"POD\",container!=\"\"}/1024/1024/1024) by (container, pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\",resource=\"cpu\"}) by (container, pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\",resource=\"cpu\"}) by (container, pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\",resource=\"memory\"}/1024/1024/1024) by (container, pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\",resource=\"memory\"}/1024/1024/1024) by (container, pod)"
    }
   ]
  }
 ]
}