{
 "title": "node-resources",
 "tags": [
  "kubernetes",
  "nodes",
  "resources"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "CPU (cores)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "system",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(count(node_cpu_seconds_total{mode=\"idle\"}) by (instance) - avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) by (instance) * count(node_cpu_seconds_total{mode=\"idle\"}) by (instance))"
    }
   ]
  },
  {
   "title": "cluster",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{id=\"/\"}[5m]))"
    }
   ]
  },
  {
   "title": "cluster requests",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_resourcequota{resource=\"requests.cpu\", type=\"hard\"})"
    }
   ]
  },
  {
   "title": "cluster limits",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_resourcequota{resource=\"limits.cpu\", type=\"hard\"})"
    }
   ]
  },
  {
   "title": "CPU over time (cores)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "server",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(count(node_cpu_seconds_total{mode=\"idle\"}) by (instance) - avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) by (instance) * count(node_cpu_seconds_total{mode=\"idle\"}) by (instance))"
      }
     ]
    },
    {
     "title": "cluster",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{container!=\"POD\",container!=\"\"}[5m])) by (namespace)",
       "legendFormat": "{{namespace}} usage"
      }
     ]
    },
    {
     "title": "cluster requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(kube_resourcequota{resource=\"requests.cpu\", type=\"hard\"}) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "cluster limits",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(kube_resourcequota{resource=\"limits.cpu\", type=\"hard\"}) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    }
   ]
  },
  { "title": "RAM (GiB)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "system",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg((node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Cached_bytes - node_memory_Buffers_bytes) / 1024 / 1024 / 1024)",
     "legendFormat": "active memory use"
    },
    {
     "expr": "avg((node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / 1024 / 1024 / 1024)",
     "legendFormat": "memory pressure"
    }
   ]
  },
  {
   "title": "cluster",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(container_memory_working_set_bytes{id=\"/\"}) / 1024 / 1024 / 1024"
    }
   ]
  },
  {
   "title": "cluster requests",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_resourcequota{resource=\"requests.memory\", type=\"hard\"}) / 1024 / 1024 / 1024"
    }
   ]
  },
  {
   "title": "cluster limits",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_resourcequota{resource=\"limits.memory\", type=\"hard\"}) / 1024 / 1024 / 1024"
    }
   ]
  },
  {
   "title": "RAM over time (GiB)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "system",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg((node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Cached_bytes - node_memory_Buffers_bytes) / 1024 / 1024 / 1024)"
      }
     ]
    },
    {
     "title": "cluster",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{container!=\"POD\",container!=\"\"}) by (namespace) / 1024 / 1024 / 1024",
       "legendFormat": "{{namespace}} usage"
      }
     ]
    },
    {
     "title": "cluster requests",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(kube_resourcequota{resource=\"requests.memory\", type=\"hard\"}/1024/1024/1024) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "cluster limits",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(kube_resourcequota{resource=\"limits.memory\", type=\"hard\"}/1024/1024/1024) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    }
   ]
  },
  { "title": "GPU 0 (GTX 960)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "utilization (%)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(DCGM_FI_DEV_GPU_UTIL{gpu=\"0\"})",
     "legendFormat": "system"
    },
    {
     "expr": "max(DCGM_FI_DEV_GPU_UTIL{gpu=\"0\"})",
     "legendFormat": "cluster"
    }
   ]
  },
  {
   "title": "VRAM (GiB)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(DCGM_FI_DEV_FB_USED{gpu=\"0\"}) / 1024",
     "legendFormat": "system"
    },
    {
     "expr": "max(DCGM_FI_DEV_FB_USED{gpu=\"0\"}) / 1024",
     "legendFormat": "cluster"
    }
   ]
  },
  { "title": "GPU 1 (RTX 3060)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "utilization (%)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(DCGM_FI_DEV_GPU_UTIL{gpu=\"1\"})",
     "legendFormat": "system"
    },
    {
     "expr": "max(DCGM_FI_DEV_GPU_UTIL{gpu=\"1\"})",
     "legendFormat": "cluster"
    }
   ]
  },
  {
   "title": "VRAM (GiB)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(DCGM_FI_DEV_FB_USED{gpu=\"1\"}) / 1024",
     "legendFormat": "system"
    },
    {
     "expr": "max(DCGM_FI_DEV_FB_USED{gpu=\"1\"}) / 1024",
     "legendFormat": "cluster"
    }
   ]
  },
  {
   "title": "GPU over time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU system",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "max(DCGM_FI_DEV_GPU_UTIL) by (gpu)",
       "legendFormat": "GPU {{gpu}}"
      }
     ]
    },
    {
     "title": "GPU cluster",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(DCGM_FI_DEV_GPU_UTIL{job=\"dcgm-exporter\", namespace!=\"\"}) by (namespace)",
       "legendFormat": "{{namespace}}"
      },
      {
       "expr": "sum(DCGM_FI_DEV_GPU_UTIL{job=\"dcgm-exporter\", namespace=\"\"})",
       "legendFormat": "unallocated"
      }
     ]
    },
    {
     "title": "VRAM system",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max(DCGM_FI_DEV_FB_USED) by (gpu) / 1024",
       "legendFormat": "GPU {{gpu}}"
      }
     ]
    },
    {
     "title": "VRAM cluster",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(DCGM_FI_DEV_FB_USED{job=\"dcgm-exporter\", namespace!=\"\"}) by (namespace) / 1024",
       "legendFormat": "{{namespace}}"
      },
      {
       "expr": "sum(DCGM_FI_DEV_FB_USED{job=\"dcgm-exporter\", namespace=\"\"}) / 1024",
       "legendFormat": "unallocated"
      }
     ]
    }
   ]
  },
  { "title": "additional metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "storage usage by device (GiB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{id=\"/\",device=~\"/dev/.*\"}) by (device) / 1024 / 1024 / 1024",
     "legendFormat": "{{ device | reReplaceAll \"/dev/mapper/datavg-\" \"\" | reReplaceAll \"/dev/\" \"\" | reReplaceAll \"--\" \"-\" }}"
    }
   ]
  },
  {
   "title": "network I/O by namespace (MiB/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace!=\"\"}[5m]) + rate(container_network_transmit_bytes_total{namespace!=\"\"}[5m])) by (namespace) / 1024 / 1024",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "namespace resource summary",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_resourcequota{resource=\"requests.cpu\", type=\"hard\"}) by (namespace)"
    },
    {
     "expr": "sum(kube_resourcequota{resource=\"limits.cpu\", type=\"hard\"}) by (namespace)"
    },
    {
     "expr": "sum(kube_resourcequota{resource=\"requests.memory\", type=\"hard\"}/1024/1024/1024) by (namespace)"
    },
    {
     "expr": "sum(kube_resourcequota{resource=\"limits.memory\", type=\"hard\"}/1024/1024/1024) by (namespace)"
    }
   ]
  }
 ]
}