apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

nameSuffix: -prod

patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: wst-flyway
      namespace: pgsql
    spec:
      template:
        metadata:
          labels:
            environment: prod
        spec:
          initContainers:
          - name: wst-flyway-migrate
            image: ghcr.io/x81k25/wst-flyway:main
            envFrom:
            - configMapRef:
                name: flyway-config-prod
            - secretRef:
                name: flyway-secrets-prod
          containers:
          - name: wst-flyway-main
            image: ghcr.io/x81k25/wst-flyway:main
  target:
    kind: Deployment
    name: wst-flyway

patchesStrategicMerge:
- cronjob-restart-patch.yaml

commonLabels:
  environment: prod