# minio/overlays/dev/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- configmap-ref.yaml
namespace: pgsql
nameSuffix: -dev
commonLabels:
  variant: dev
  environment: dev

replacements:
- source:
    kind: ConfigMap
    name: minio-config-dev
    fieldPath: data.MINIO_PORT_EXTERNAL_API
  targets:
  - select:
      kind: Service
      name: minio
    fieldPaths:
    - spec.ports.[name=api].nodePort
- source:
    kind: ConfigMap
    name: minio-config-dev
    fieldPath: data.MINIO_PORT_EXTERNAL_CONSOLE
  targets:
  - select:
      kind: Service
      name: minio
    fieldPaths:
    - spec.ports.[name=console].nodePort


patches:
# MinIO Deployment Patch
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: minio
    spec:
      template:
        spec:
          containers:
          - name: minio
            env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: minio-secrets-dev
                  key: MINIO_ACCESS_KEY
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-secrets-dev
                  key: MINIO_SECRET_KEY
            - name: MINIO_PORT_EXTERNAL
              valueFrom:
                configMapKeyRef:
                  name: minio-config-dev
                  key: MINIO_PORT_EXTERNAL
          volumes:
          - name: minio-data
            hostPath:
              path: /d/k8s/volumes/minio/dev/data
              type: DirectoryOrCreate

