# minio/overlays/dev/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: pgsql
nameSuffix: -dev
commonLabels:
  variant: dev
  environment: dev

patches:
# MinIO Deployment Patch
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: minio
    spec:
      template:
        spec:
          containers:
          - name: minio
            env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: minio-secrets-dev
                  key: MINIO_ACCESS_KEY
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-secrets-dev
                  key: MINIO_SECRET_KEY
          volumes:
          - name: minio-data
            hostPath:
              path: /d/k8s/volumes/minio/dev/data
              type: DirectoryOrCreate

# MinIO Service Patch
- target:
    version: v1
    kind: Service
    name: minio
  patch: |-
    - op: replace
      path: /spec/ports/0/nodePort
      value: 30902
    - op: replace
      path: /spec/ports/1/nodePort
      value: 30903