# ArgoCD ApplicationSet for center-console-dev with Image Updater
# Apply: kubectl apply -f center-console-dev-appset.yaml
# Delete: kubectl delete applicationset center-console-dev-appset -n argocd

apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: center-console-dev-appset
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: center-console
        path: media/center-console/overlays/dev
  template:
    metadata:
      name: '{{name}}-dev'
      annotations:
        argocd-image-updater.argoproj.io/image-list: "center-console=ghcr.io/x81k25/center-console:dev"
        argocd-image-updater.argoproj.io/center-console.update-strategy: "digest"
        argocd-image-updater.argoproj.io/center-console.pull-secret: "pullsecret:argocd/ghcr-image-updater-secret"
        argocd-image-updater.argoproj.io/write-back-method: "git"
        argocd-image-updater.argoproj.io/git-branch: "main"
        argocd-image-updater.argoproj.io/write-back-target: "kustomization:media/center-console/overlays/dev"
    spec:
      project: default
      source:
        repoURL: https://github.com/x81k25/k8s-manifests.git
        targetRevision: HEAD
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "media-dev"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true