# ./app.yaml
# patch command:
## kubectl apply -f media-prod-appset.yaml
# delete appset
## kubectl delete applicationset media-prod-appset -n argocd

apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: media-prod-appset
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: atd-prod
        path: media/atd/overlays/prod
      - name: center-console-prod
        path: media/center-console/overlays/prod
      - name: rear-diff-prod
        path: media/rear-diff/overlays/prod
      - name: atd-music
        path: media/atd/overlays/music
      - name: plex-prod
        path: media/plex/overlays/prod
      - name: dagster-prod
        path: media/dagster/overlays/prod
  template:
    metadata:
      name: '{{name}}'
      annotations:
        argocd-image-updater.argoproj.io/image-list: "center-console=ghcr.io/x81k25/center-console:main,rear-diff-prod=ghcr.io/x81k25/rear-differential:main,dagster-prod=ghcr.io/x81k25/dagstributor:main"
        argocd-image-updater.argoproj.io/center-console.update-strategy: "digest"
        argocd-image-updater.argoproj.io/center-console.pull-secret: "pullsecret:argocd/ghcr-image-updater-pull"
        argocd-image-updater.argoproj.io/rear-diff-prod.update-strategy: "digest"
        argocd-image-updater.argoproj.io/rear-diff-prod.pull-secret: "pullsecret:argocd/ghcr-image-updater-pull"
        argocd-image-updater.argoproj.io/dagster-prod.update-strategy: "digest"
        argocd-image-updater.argoproj.io/dagster-prod.pull-secret: "pullsecret:argocd/ghcr-image-updater-pull"
        argocd-image-updater.argoproj.io/write-back-method: "git"
        argocd-image-updater.argoproj.io/git-branch: "main"
    spec:
      project: default
      source:
        repoURL: git@github.com:x81k25/k8s-manifests.git
        targetRevision: HEAD
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "media-prod"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true