# patch command:
## kubectl apply -f ./media/media-stg-appset.yaml
# delete appset
## kubectl delete applicationset media-stg-appset -n argocd

apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: media-stg-appset
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: atd
        path: media/atd/overlays
      - name: center-console
        path: media/center-console/overlays
      - name: rear-diff
        path: media/rear-diff/overlays
      - name: dagster
        path: media/dagster/overlays
  template:
    metadata:
      name: '{{name}}-stg'
      annotations:
        argocd-image-updater.argoproj.io/image-list: >-
          center-console=ghcr.io/x81k25/center-console:stg,
          rear-diff=ghcr.io/x81k25/rear-differential:stg,
          dagstributor=ghcr.io/x81k25/dagstributor:stg
        argocd-image-updater.argoproj.io/center-console.update-strategy: "digest"
        argocd-image-updater.argoproj.io/rear-diff.update-strategy: "digest"
        argocd-image-updater.argoproj.io/dagstributor.update-strategy: "digest"
        argocd-image-updater.argoproj.io/write-back-method: "git"
        argocd-image-updater.argoproj.io/git-branch: "main"
    spec:
      project: default
      source:
        repoURL: git@github.com:x81k25/k8s-manifests.git
        targetRevision: HEAD
        path: "{{path}}/stg"
      destination:
        server: https://kubernetes.default.svc
        namespace: "media-stg"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
 