# ./app.yaml
# patch command:
## kubectl apply -f media-dev-appset.yaml
# delete appset
## kubectl delete applicationset media-dev-appset -n argocd

apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: media-dev-appset
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: atd
        path: media/atd/overlays
      - name: rear-diff
        path: media/rear-diff/overlays
      - name: plex
        path: media/plex/overlays
      - name: dagster
        path: media/dagster/overlays
  template:
    metadata:
      name: '{{name}}-dev'
      annotations:
        argocd-image-updater.argoproj.io/image-list: "rear-diff=ghcr.io/x81k25/rear-differential:dev,dagster=ghcr.io/x81k25/dagstributor:dev"
        argocd-image-updater.argoproj.io/rear-diff.update-strategy: "digest"
        argocd-image-updater.argoproj.io/rear-diff.pull-secret: "pullsecret:argocd/ghcr-image-updater-pull"
        argocd-image-updater.argoproj.io/dagster.update-strategy: "digest"
        argocd-image-updater.argoproj.io/dagster.pull-secret: "pullsecret:argocd/ghcr-image-updater-pull"
        argocd-image-updater.argoproj.io/write-back-method: "git"
        argocd-image-updater.argoproj.io/git-branch: "main"
    spec:
      project: default
      source:
        repoURL: https://github.com/x81k25/k8s-manifests.git
        targetRevision: HEAD
        path: "{{path}}/dev"
      destination:
        server: https://kubernetes.default.svc
        namespace: "media-dev"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
 