apiVersion: apps/v1
kind: Deployment
metadata:
  name: wst-flyway
  namespace: pgsql
  labels:
    app: wst-flyway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wst-flyway
  template:
    metadata:
      labels:
        app: wst-flyway
    spec:
      imagePullSecrets:
      - name: github-secrets
      initContainers:
      - name: wst-flyway-migrate
        image: ghcr.io/x81k25/wst-flyway:sha-1dc332f
        imagePullPolicy: Always
        env:
        - name: FLYWAY_URL
          value: "jdbc:postgresql://$(FLYWAY_PGSQL_HOST):$(FLYWAY_PGSQL_PORT)/$(FLYWAY_PGSQL_DATABASE)"
        - name: FLYWAY_USER
          valueFrom:
            secretKeyRef:
              name: wst-flyway-secrets
              key: FLYWAY_PGSQL_USERNAME
        - name: FLYWAY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wst-flyway-secrets
              key: FLYWAY_PGSQL_PASSWORD
        - name: FLYWAY_PGSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: wst-flyway-config
              key: FLYWAY_PGSQL_HOST
        - name: FLYWAY_PGSQL_PORT
          valueFrom:
            configMapKeyRef:
              name: wst-flyway-config
              key: FLYWAY_PGSQL_PORT
        - name: FLYWAY_PGSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: wst-flyway-config
              key: FLYWAY_PGSQL_DATABASE
        args: ["migrate"]
      containers:
      - name: wst-flyway-main
        image: ghcr.io/x81k25/wst-flyway:sha-1dc332f
        imagePullPolicy: Always
        command: ["sleep", "infinity"]
        resources:
          requests:
            memory: "64Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "50m"