apiVersion: apps/v1
kind: Deployment
metadata:
  name: wst-flyway
  namespace: pgsql
  labels:
    app: wst-flyway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wst-flyway
  template:
    metadata:
      labels:
        app: wst-flyway
    spec:
      imagePullSecrets:
      - name: github-secrets
      containers:
      - name: wst-flyway-container
        image: ghcr.io/x81k25/wst-flyway:sha-1dc332f
        env:
        - name: FLYWAY_PGSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: flyway-config
              key: FLYWAY_PGSQL_HOST
        - name: FLYWAY_PGSQL_PORT
          valueFrom:
            configMapKeyRef:
              name: flyway-config
              key: FLYWAY_PGSQL_PORT
        - name: FLYWAY_PGSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: flyway-config
              key: FLYWAY_PGSQL_DATABASE
        - name: FLYWAY_PGSQL_USERNAME
          valueFrom:
            secretKeyRef:
              name: flyway-secrets
              key: FLYWAY_PGSQL_USERNAME
        - name: FLYWAY_PGSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: flyway-secrets
              key: FLYWAY_PGSQL_PASSWORD
        command: ["npm", "run", "migrate"]
      restartPolicy: Always