apiVersion: v1
kind: ServiceAccount
metadata:
  name: wst-flyway-restart-sa
  namespace: pgsql
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: wst-flyway-restart-role
  namespace: pgsql
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  resourceNames: ["wst-flyway"]
  verbs: ["get", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments/scale"]
  resourceNames: ["wst-flyway"]
  verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wst-flyway-restart-rb
  namespace: pgsql
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: wst-flyway-restart-role
subjects:
- kind: ServiceAccount
  name: wst-flyway-restart-sa
  namespace: pgsql