apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: observability-appset
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: fluent-bit
        path: observability/fluent-bit
      - name: loki
        path: observability/loki
      - name: grafana
        path: observability/grafana
      - name: prometheus
        path: observability/prometheus/base
      - name: kube-state-metrics
        path: observability/kube-state-metrics/base
  template:
    metadata:
      name: '{{name}}'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: git@github.com:x81k25/k8s-manifests.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: observability
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true