#./overlays/dev/kustomizaton.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
nameSuffix: -dev
commonLabels:
  variant: dev
patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: atd
    spec:
      template:
        spec:
          containers:
          - name: automatic-transmission-daemon
            image: ghcr.io/x81k25/automatic-transmission-daemon:dev
            env:
            - name: http_proxy
              value: "http://vpn-gateway.media-dev:8118"
            - name: https_proxy
              value: "http://vpn-gateway.media-dev:8118"          
            volumeMounts:
            - name: complete-volume
              mountPath: /media-cache/dev/complete
            - name: incomplete-volume
              mountPath: /media-cache/dev/incomplete
          volumes:
          - name: complete-volume
            hostPath:
              path: /d/media-cache/dev/complete
          - name: incomplete-volume
            hostPath:
              path: /d/media-cache/dev/incomplete
- target:
    version: v1
    kind: Service
    name: atd
  patch: |-
    - op: replace
      path: /spec/ports/0/port
      value: 9093
    - op: replace
      path: /spec/ports/0/nodePort
      value: 30093