apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  type: NodePort
  ports:
  - port: 9000
    targetPort: 9000
    nodePort: 32000
    name: api
  - port: 9001
    targetPort: 9001
    nodePort: 32001
    name: console
  selector:
    app: minio