# patch command:
## kubectl apply -f ./gitlab/gitlab-appset.yaml
# delete appset
## kubectl delete applicationset gitlab-appset -n argocd

apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gitlab-appset
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: gitlab-runner
        path: gitlab/gitlab-runner/base
  template:
    metadata:
      name: '{{name}}'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: git@github.com:x81k25/k8s-manifests.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: gitlab
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
