# mlflow/base/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  labels:
    app: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: mlflow
        image: ghcr.io/mlflow/mlflow-postgres:latest
        imagePullPolicy: Always
        command: ["/bin/bash", "-c"]
        args:
        - |
          pip install psycopg2-binary
          mlflow server \
            --host=0.0.0.0 \
            --port=5000 \
            --backend-store-uri=postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME} \
            --default-artifact-root=s3://${BUCKET_NAME}/ \
            --gunicorn-opts '--log-level debug --timeout 120 --workers 2'
        ports:
        - containerPort: 5000
        env:
        - name: MLFLOW_S3_ENDPOINT_URL
          value: "http://minio:9000"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: minio_access_key
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: minio_secret_key
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mlflow-db-secret
              key: db_user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mlflow-db-secret
              key: db_password
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: mlflow-db-secret
              key: db_host
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: mlflow-db-secret
              key: db_port
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: mlflow-db-secret
              key: db_name
        - name: BUCKET_NAME
          valueFrom:
            secretKeyRef:
              name: mlflow-artifact-store-secret
              key: bucket_name
        volumeMounts:
        - name: logs
          mountPath: /mlflow/logs
      volumes:
      - name: logs
        hostPath:
          path: /d/k8s/volumes/mlflow/ENV/logs
          type: DirectoryOrCreate