apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: observability
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
        prometheus.io/path: "/metrics"
    spec:
      securityContext:
        fsGroup: 472
      initContainers:
      - name: fix-permissions
        image: busybox:1.35
        command: ['sh', '-c', 'mkdir -p /var/lib/grafana && chown -R 472:472 /var/lib/grafana']
        volumeMounts:
        - name: storage
          mountPath: /var/lib/grafana
        securityContext:
          runAsUser: 0
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /etc/grafana
        - name: datasources
          mountPath: /etc/grafana/provisioning/datasources
        - name: dashboard-provider
          mountPath: /etc/grafana/provisioning/dashboards
        - name: dashboards-k8s-node-status
          mountPath: /var/lib/grafana/dashboards/k8s-node-status.json
          subPath: k8s-node-status.json
        - name: storage
          mountPath: /var/lib/grafana
        env:
        - name: GF_SECURITY_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: grafana-credentials
              key: username
              optional: false
        - name: GF_SECURITY_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: grafana-credentials
              key: password
              optional: false
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 10
        securityContext:
          runAsUser: 472
          runAsNonRoot: true
      volumes:
      - name: config
        configMap:
          name: grafana-config
      - name: datasources
        configMap:
          name: grafana-datasources
      - name: dashboard-provider
        configMap:
          name: grafana-dashboard-provider
      - name: dashboards-k8s-resources
        configMap:
          name: grafana-dashboard-k8s-resources
      - name: dashboards-k8s-pod-monitoring
        configMap:
          name: grafana-dashboard-k8s-pod-monitoring
      - name: dashboards-k8s-namespace-overview
        configMap:
          name: grafana-dashboard-k8s-namespace-overview
      - name: dashboards-k8s-node-overview
        configMap:
          name: grafana-dashboard-k8s-node-overview
      - name: dashboards-6417
        configMap:
          name: grafana-dashboard-6417
      - name: dashboards-315
        configMap:
          name: grafana-dashboard-315
      - name: dashboards-12114
        configMap:
          name: grafana-dashboard-12114
      - name: dashboards-8588
        configMap:
          name: grafana-dashboard-8588
      - name: dashboards-k8s-node-status
        configMap:
          name: grafana-dashboard-k8s-node-status
      - name: storage
        hostPath:
          path: /d/k8s/volumes/observability/grafana/data
          type: DirectoryOrCreate