apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: observability
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      securityContext:
        fsGroup: 472
      initContainers:
      - name: fix-permissions
        image: busybox:1.35
        command: ['sh', '-c', 'rm -rf /var/lib/grafana/* && mkdir -p /var/lib/grafana && chown -R 472:472 /var/lib/grafana']
        volumeMounts:
        - name: storage
          mountPath: /var/lib/grafana
        securityContext:
          runAsUser: 0
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /etc/grafana
        - name: datasources
          mountPath: /etc/grafana/provisioning/datasources
        - name: storage
          mountPath: /var/lib/grafana
        env:
        - name: GF_SECURITY_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: grafana-credentials
              key: username
              optional: false
        - name: GF_SECURITY_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: grafana-credentials
              key: password
              optional: false
        resources:
          limits:
            cpu: 250m
            memory: 750Mi
          requests:
            cpu: 100m
            memory: 250Mi
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 10
        securityContext:
          runAsUser: 472
          runAsNonRoot: true
      volumes:
      - name: config
        configMap:
          name: grafana-config
      - name: datasources
        configMap:
          name: grafana-datasources
      - name: storage
        hostPath:
          path: /d/k8s/volumes/observability/grafana/data
          type: DirectoryOrCreate