apiVersion: v1
kind: Service
metadata:
  name: cici-mouth
  namespace: ai-ml
  labels:
    app: cici-mouth
spec:
  type: NodePort
  ports:
  - port: 8001
    targetPort: 8001
    nodePort: 30213
  selector:
    app: cici-mouth
