# mlflow/overlays/prod/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: ai-ml
nameSuffix: -prod
commonLabels:
  variant: prod
  environment: prod

patches:
# MLflow Deployment Patch
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: mlflow
    spec:
      template:
        spec:
          containers:
          - name: mlflow
            env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mlflow-prod-secret
                  key: mlflow_prod_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mlflow-prod-secret
                  key: mlflow_prod_password
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: mlflow-prod-secret
                  key: mlflow_prod_name
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: mlflow-prod-secret
                  key: mlflow_prod_port
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mlflow-prod-secret
                  key: mlflow_prod_database
          volumes:
          - name: logs
            hostPath:
              path: /d/k8s/volumes/mlflow/prod/logs
          - name: python-packages
            hostPath:
              path: /d/k8s/volumes/mlflow/prod/packages
              type: DirectoryOrCreate
          - name: artifacts
            hostPath:
              path: /d/k8s/volumes/mlflow/prod/artifacts
              type: DirectoryOrCreate

# MLflow Service Patch
- target:
    version: v1
    kind: Service
    name: mlflow
  patch: |-
    - op: replace
      path: /spec/ports/0/nodePort
      value: 30500