# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test-pull-image-app
  namespace: argocd-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-test-pull-image-app
  template:
    metadata:
      labels:
        app: nginx-test-pull-image-app
    spec:
      imagePullSecrets:
      - name: ghcr-pull-image-token 
      containers:
      - name: nginx-test-pull-image-app
        image: ghcr.io/x81k25/nginx-test-pull-image-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080