# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test
  labels:
    app: nginx-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-test
  template:
    metadata:
      labels:
        app: nginx-test
    spec:
      containers:
      - name: nginx
        image: ghcr.io/${GITHUB_USERNAME}/nginx-test-pull-image-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: DOCKER_REGISTRY
          value: ghcr.io
        - name: DOCKER_USERNAME
          valueFrom:
            secretKeyRef:
              name: ghcr-pull-secrets
              key: username
        - name: DOCKER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ghcr-pull-secrets
              key: password
      imagePullSecrets:
      - name: ghcr-pull-secrets