# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test-pull-image-app
spec:
  replicas: 1
  selector:
  template:
    metadata:
      labels:
        app: nginx-test-pull-image-app
    spec:
      containers:
      - name: nginx
        image: ghcr.io/${GITHUB_USERNAME}/nginx-test-pull-image-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: ghcr-pull-image-token