# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-test-pull-image-app
spec:
  selector:
    app: nginx-test-pull-image-app
  ports:
  - port: 8080
    targetPort: 80
  type: ClusterIP
