# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-test
spec:
  selector:
    app: nginx-test
  ports:
  - port: 8080
    targetPort: 80
  type: ClusterIP
---
# secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-pull-secrets
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ${BASE64_ENCODED_DOCKER_CONFIG}