# mlflow/base/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  labels:
    app: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      imagePullSecrets:
      - name: ghcr-pull-image-token 
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: mlflow
        image: python:3.10-slim
        imagePullPolicy: Always
        command: ["/bin/bash", "-c"]
        args:
        - |
          # Install MLflow and psycopg2 to a custom location
          export PYTHONUSERBASE=/packages
          pip install --user mlflow psycopg2-binary
          export PYTHONPATH="$PYTHONPATH:/packages/lib/python3.10/site-packages"
          export PATH="$PATH:/packages/bin"
          
          mlflow server \
            --host=0.0.0.0 \
            --port=5000 \
            --backend-store-uri=postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME} \
            --default-artifact-root=file:///mlflow/artifacts \
            --gunicorn-opts '--log-level debug --timeout 120 --workers 2'
        ports:
        - containerPort: 5000
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mlflow-db-secret
              key: db_user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mlflow-db-secret
              key: db_password
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: mlflow-db-secret
              key: db_host
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: mlflow-db-secret
              key: db_port
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: mlflow-db-secret
              key: db_name
        volumeMounts:
        - name: logs
          mountPath: /mlflow/logs
        - name: python-packages
          mountPath: /packages
        - name: artifacts
          mountPath: /mlflow/artifacts
      volumes:
      - name: logs
        hostPath:
          path: /d/k8s/volumes/mlflow/ENV/logs
          type: DirectoryOrCreate
      - name: python-packages
        hostPath:
          path: /d/k8s/volumes/mlflow/ENV/packages
          type: DirectoryOrCreate
      - name: artifacts
        hostPath:
          path: /d/k8s/volumes/mlflow/ENV/artifacts
          type: DirectoryOrCreate