# mlflow/base/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  labels:
    app: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      imagePullSecrets:
      - name: ghcr-pull-image-token 
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: mlflow
        image: python:3.10-slim
        imagePullPolicy: Always
        command: ["/bin/bash", "-c"]
        args:
        - |
          # Install MLflow and psycopg2 to a custom location
          export PYTHONUSERBASE=/packages
          pip install --user mlflow psycopg2-binary boto3
          export PYTHONPATH="$PYTHONPATH:/packages/lib/python3.10/site-packages"
          export PATH="$PATH:/packages/bin"
          
          # Set MinIO environment variables for S3 compatibility
          export AWS_ACCESS_KEY_ID=${MLFLOW_MINIO_AWS_ACCESS_KEY_ID}
          export AWS_SECRET_ACCESS_KEY=${MLFLOW_MINIO_AWS_SECRET_ACCESS_KEY}
          
          # Use external MinIO endpoint for artifact URLs (so external clients can access)
          export MLFLOW_S3_ENDPOINT_URL=${MLFLOW_MINIO_ENDPOINT_EXTERNAL}:${MLFLOW_MINIO_PORT_EXTERNAL}
          
          mlflow server \
            --host=0.0.0.0 \
            --port=5000 \
            --backend-store-uri=postgresql://${MLFLOW_PGSQL_USERNAME}:${MLFLOW_PGSQL_PASSWORD}@${MLFLOW_PGSQL_HOST}:${MLFLOW_PGSQL_PORT}/${MLFLOW_PGSQL_DATABASE} \
            --default-artifact-root=${MLFLOW_MINIO_DEFAULT_ARTIFACT_ROOT} \
            --gunicorn-opts '--log-level debug --timeout 120 --workers 2'
        ports:
        - containerPort: 5000
        env:
        # ConfigMap values
        - name: MLFLOW_UID
          valueFrom:
            configMapKeyRef:
              name: mlflow-config-ENV
              key: MLFLOW_UID
        - name: MLFLOW_GID
          valueFrom:
            configMapKeyRef:
              name: mlflow-config-ENV
              key: MLFLOW_GID
        - name: MLFLOW_PORT_EXTERNAL
          valueFrom:
            configMapKeyRef:
              name: mlflow-config-ENV
              key: MLFLOW_PORT_EXTERNAL
        - name: MLFLOW_PATH_LOGS
          valueFrom:
            configMapKeyRef:
              name: mlflow-config-ENV
              key: MLFLOW_PATH_LOGS
        - name: MLFLOW_PATH_PACKAGES
          valueFrom:
            configMapKeyRef:
              name: mlflow-config-ENV
              key: MLFLOW_PATH_PACKAGES
        - name: MLFLOW_PGSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: mlflow-config-ENV
              key: MLFLOW_PGSQL_HOST
        - name: MLFLOW_PGSQL_PORT
          valueFrom:
            configMapKeyRef:
              name: mlflow-config-ENV
              key: MLFLOW_PGSQL_PORT
        - name: MLFLOW_PGSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mlflow-config-ENV
              key: MLFLOW_PGSQL_DATABASE
        - name: MLFLOW_MINIO_DEFAULT_ARTIFACT_ROOT
          valueFrom:
            configMapKeyRef:
              name: mlflow-config-ENV
              key: MLFLOW_MINIO_DEFAULT_ARTIFACT_ROOT
        - name: MLFLOW_MINIO_ENDPOINT_EXTERNAL
          valueFrom:
            configMapKeyRef:
              name: mlflow-config-ENV
              key: MLFLOW_MINIO_ENDPOINT_EXTERNAL
        - name: MLFLOW_MINIO_ENDPOINT_INTERNAL
          valueFrom:
            configMapKeyRef:
              name: mlflow-config-ENV
              key: MLFLOW_MINIO_ENDPOINT_INTERNAL
        - name: MLFLOW_MINIO_PORT_EXTERNAL
          valueFrom:
            configMapKeyRef:
              name: mlflow-config-ENV
              key: MLFLOW_MINIO_PORT_EXTERNAL
        - name: MLFLOW_MINIO_PORT_INTERNAL
          valueFrom:
            configMapKeyRef:
              name: mlflow-config-ENV
              key: MLFLOW_MINIO_PORT_INTERNAL
        # Secret values
        - name: MLFLOW_USERNAME
          valueFrom:
            secretKeyRef:
              name: mlflow-secrets-ENV
              key: MLFLOW_USERNAME
        - name: MLFLOW_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mlflow-secrets-ENV
              key: MLFLOW_PASSWORD
        - name: MLFLOW_PGSQL_USERNAME
          valueFrom:
            secretKeyRef:
              name: mlflow-secrets-ENV
              key: MLFLOW_PGSQL_USERNAME
        - name: MLFLOW_PGSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mlflow-secrets-ENV
              key: MLFLOW_PGSQL_PASSWORD
        - name: MLFLOW_MINIO_AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: mlflow-secrets-ENV
              key: MLFLOW_MINIO_AWS_ACCESS_KEY_ID
        - name: MLFLOW_MINIO_AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: mlflow-secrets-ENV
              key: MLFLOW_MINIO_AWS_SECRET_ACCESS_KEY
        volumeMounts:
        - name: logs
          mountPath: /mlflow/logs
        - name: python-packages
          mountPath: /packages
      volumes:
      - name: logs
        hostPath:
          path: /d/k8s/volumes/mlflow/ENV/logs
          type: DirectoryOrCreate
      - name: python-packages
        hostPath:
          path: /d/k8s/volumes/mlflow/ENV/packages
          type: DirectoryOrCreate