# rear-differential/overlays/dev/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: media-dev
nameSuffix: -dev
commonLabels:
  variant: dev
patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: rear-differential
    spec:
      template:
        spec:
          containers:
          - name: rear-differential-api
            image: ghcr.io/x81k25/rear-differential:dev
            env:
            - name: LOG_LEVEL
              value: "DEBUG"
- target:
    version: v1
    kind: Service
    name: rear-differential
  patch: |-
    - op: replace
      path: /spec/ports/0/nodePort
      value: 30802