apiVersion: v1
kind: Service
metadata:
  name: kube-state-metrics
  namespace: observability
  labels:
    app: kube-state-metrics
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http-metrics
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: telemetry
  selector:
    app: kube-state-metrics