# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app-kustomize
  labels:
    app: test-app-kustomize
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app-kustomize
  template:
    metadata:
      labels:
        app: test-app-kustomize
    spec:
      containers:
      - name: nginx
        image: nginx:1.25.3
        ports:
        - containerPort: 80