# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-test-kustomize-app-service
spec:
  selector:
    app: nginx-test-kustomize-app
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP