# pgsql/overlays/stg/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namePrefix: stg-
patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: postgres
      namespace: pgsql
    spec:
      template:
        spec:
          containers:
          - name: postgres
            env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: pgsql-stg-config
                  key: pgsql_stg_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgsql-stg-config
                  key: pgsql_stg_password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: pgsql-stg-config
                  key: pgsql_stg_database
          volumes:
          - name: postgres-data
            hostPath:
              path: /d/postgres/stg
  target:
    kind: Deployment
    name: postgres
    namespace: pgsql
- patch: |-
    apiVersion: v1
    kind: Service
    metadata:
      name: postgres
      namespace: pgsql
    spec:
      $patch: replace
      type: NodePort
      ports:
      - port: 5433
        targetPort: 5432
        name: postgres
        protocol: TCP
      selector:
        app: postgres
  target:
    kind: Service
    name: postgres
    namespace: pgsql