# mlflow-appset.yaml
# apply:
# kubectl apply -f ai-ml-appset.yaml
# delete:
# kubectl delete applicationset ai-ml-appset -n argocd

apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ai-ml-appset
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: reel-driver-dev
        path: ai-ml/reel-driver/overlays/dev
        environment: dev
      - name: reel-driver-stg
        path: ai-ml/reel-driver/overlays/stg
        environment: stg
      - name: reel-driver-prod
        path: ai-ml/reel-driver/overlays/prod
        environment: prod
      - name: mlflow-dev
        path: ai-ml/mlflow/overlays/dev
        environment: dev
      - name: mlflow-stg
        path: ai-ml/mlflow/overlays/stg
        environment: stg
      - name: mlflow-prod
        path: ai-ml/mlflow/overlays/prod
        environment: prod
        
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: git@github.com:x81k25/k8s-manifests.git
        targetRevision: HEAD
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "ai-ml"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true