# ai-ml-cici-appset.yaml
# apply:
# kubectl apply -f ai-ml-cici-appset.yaml
# delete:
# kubectl delete applicationset ai-ml-cici-appset -n argocd

apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ai-ml-cici-appset
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: cici-mind
        path: ai-ml/cici-mind
        image: 192.168.50.2:5050/ai-ml/cici/mind:latest
      - name: cici-face
        path: ai-ml/cici-face
        image: 192.168.50.2:5050/ai-ml/cici/face:latest
      - name: cici-ears
        path: ai-ml/cici-ears
        image: 192.168.50.2:5050/ai-ml/cici/ears:latest
      - name: cici-mouth
        path: ai-ml/cici-mouth
        image: 192.168.50.2:5050/ai-ml/cici/mouth:latest
  template:
    metadata:
      name: '{{name}}'
      annotations:
        argocd-image-updater.argoproj.io/image-list: "cici={{image}}"
        argocd-image-updater.argoproj.io/write-back-method: git
        argocd-image-updater.argoproj.io/git-branch: main
        argocd-image-updater.argoproj.io/cici.update-strategy: digest
    spec:
      project: default
      source:
        repoURL: git@github.com:x81k25/k8s-manifests.git
        targetRevision: HEAD
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "ai-ml"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
