# ai-ml-prod-appset.yaml
# apply:
# kubectl apply -f ai-ml-prod-appset.yaml
# delete:
# kubectl delete applicationset ai-ml-prod-appset -n argocd

apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ai-ml-prod-appset
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: reel-driver-prod
        path: ai-ml/reel-driver/overlays/prod
      - name: mlflow-prod
        path: ai-ml/mlflow/overlays/prod
  template:
    metadata:
      name: '{{name}}'
      annotations:
        argocd-image-updater.argoproj.io/image-list: >-
          reel-driver-prod=ghcr.io/x81k25/reel-driver-api:main
        argocd-image-updater.argoproj.io/reel-driver-prod.update-strategy: "digest"
        argocd-image-updater.argoproj.io/write-back-method: "git"
        argocd-image-updater.argoproj.io/git-branch: "main"
    spec:
      project: default
      source:
        repoURL: git@github.com:x81k25/k8s-manifests.git
        targetRevision: HEAD
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "ai-ml"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true