# ai-ml-stg-appset.yaml
# apply:
# kubectl apply -f ai-ml-stg-appset.yaml
# delete:
# kubectl delete applicationset ai-ml-stg-appset -n argocd

apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ai-ml-stg-appset
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: reel-driver
        path: ai-ml/reel-driver/overlays
      - name: mlflow
        path: ai-ml/mlflow/overlays
  template:
    metadata:
      name: '{{name}}-stg'
      annotations:
        argocd-image-updater.argoproj.io/image-list: >-
          reel-driver=ghcr.io/x81k25/reel-driver-api:stg
        argocd-image-updater.argoproj.io/reel-driver.update-strategy: "digest"
        argocd-image-updater.argoproj.io/reel-driver.pull-secret: "pullsecret:argocd/ghcr-pull-image-secret"
        argocd-image-updater.argoproj.io/write-back-method: "git"
        argocd-image-updater.argoproj.io/git-branch: "main"
    spec:
      project: default
      source:
        repoURL: git@github.com:x81k25/k8s-manifests.git
        targetRevision: HEAD
        path: "{{path}}/stg"
      destination:
        server: https://kubernetes.default.svc
        namespace: "ai-ml"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true