# minio/overlays/prod/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: pgsql
nameSuffix: -prod
commonLabels:
  variant: prod
  environment: prod

patches:
# MinIO Deployment Patch
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: minio
    spec:
      template:
        spec:
          containers:
          - name: minio
            env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: minio-secrets-prod
                  key: MINIO_ACCESS_KEY
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-secrets-prod
                  key: MINIO_SECRET_KEY
            - name: MINIO_PORT_EXTERNAL_API
              valueFrom:
                configMapKeyRef:
                  name: minio-config-prod
                  key: MINIO_PORT_EXTERNAL_API
            - name: MINIO_PORT_EXTERNAL_CONSOLE
              valueFrom:
                configMapKeyRef:
                  name: minio-config-prod
                  key: MINIO_PORT_EXTERNAL_CONSOLE
          volumes:
          - name: minio-data
            hostPath:
              path: /d/k8s/volumes/minio/prod/data
              type: DirectoryOrCreate

# MinIO Service Patch - Using clean 31000-31009 range
# API: 31003 (to match ConfigMap MINIO_PORT_EXTERNAL_API)
# Console: 31000 (to match ConfigMap MINIO_PORT_EXTERNAL_CONSOLE)
- target:
    version: v1
    kind: Service
    name: minio
  patch: |-
    - op: replace
      path: /spec/ports/0/nodePort
      value: 31003
    - op: replace
      path: /spec/ports/1/nodePort
      value: 31000