apiVersion: apps/v1
kind: Deployment
metadata:
  name: reel-driver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reel-driver
  template:
    metadata:
      labels:
        app: reel-driver
    spec:
      containers:
      - name: reel-driver-api
        image: ghcr.io/x81k25/reel-driver-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: MODEL_PATH
          value: "/reel-driver/model_artifacts/"
        - name: LOG_LEVEL
          value: "DEBUG"
        - name: API_HOST
          value: "0.0.0.0"
        - name: API_PORT
          value: "8000"
      imagePullSecrets:
      - name: ghcr-pull-image-secret