# dagster/base/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: dagster
  labels:
    app: dagster
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30300
    protocol: TCP
    name: http
  selector:
    app: dagster