# PostgreSQL Deployment for Development Environment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-dev
  namespace: pgsql
  labels:
    app: postgres-dev
    managed-by: terraform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-dev
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres-dev
    spec:
      securityContext:
        fsGroup: 999
      containers:
      - name: postgres
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_DB
          value: postgres
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        hostPath:
          path: /mnt/data/postgres-dev
          type: DirectoryOrCreate