# PostgreSQL Deployment for Development Environment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-dev
  namespace: pgsql
  labels:
    app: postgres-dev
    managed-by: terraform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-dev
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres-dev
    spec:
      securityContext:
        fsGroup: ${var.pgsql_config.dev.security.GID}
      containers:
      - name: postgres
        image: postgres:latest
        ports:
        - containerPort: ${var.pgsql_config.dev.port}
        env:
        - name: POSTGRES_USER
          value: ${var.pgsql_config.dev.user}
        - name: POSTGRES_PASSWORD
          value: ${var.pgsql_config.dev.password}
        - name: POSTGRES_DB
          value: ${var.pgsql_config.dev.database}
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        hostPath:
          path: ${var.pgsql_config.dev.mount}
          type: DirectoryOrCreate