apiVersion: v1
kind: Service
metadata:
  name: postgres-dev
  namespace: pgsql
  labels:
    app: postgres-dev
    managed-by: terraform
spec:
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app: postgres-dev
  type: ClusterIP