# configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: centraldashboard-config
data:
  links: |
    {
      "menuLinks": [
        {
          "link": "/pipeline/",
          "name": "Pipelines"
        },
        {
          "link": "/notebook/",
          "name": "Notebooks"
        }
      ]
    }