# rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubeflow-sa
  namespace: ai-ml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubeflow-role
rules:
- apiGroups: [""]
  resources: ["nodes", "namespaces", "pods", "configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["app.k8s.io"]
  resources: ["applications"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubeflow-binding
subjects:
- kind: ServiceAccount
  name: kubeflow-sa
  namespace: ai-ml
roleRef:
  kind: ClusterRole
  name: kubeflow-role
  apiGroup: rbac.authorization.k8s.io