apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: atd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/x81k25/k8s-manifests.git
    targetRevision: HEAD
    path: atd
  destination:
    server: https://kubernetes.default.svc
    namespace: automatic-transmission
  syncPolicy:
    automated:
      prune: true
      selfHeal: true