# ./pgsql-appset.yaml
# patch command:
## kubectl apply -f ./pgsql/pgsql-appset.yaml
# delete appset
## kubectl delete applicationset pgsql-appset -n argocd

apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pgsql-appset
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: pgsql-prod
        path: pgsql/pgsql/overlays/prod
      - name: pgsql-stg
        path: pgsql/pgsql/overlays/stg
      - name: pgsql-dev
        path: pgsql/pgsql/overlays/dev
      - name: pgadmin4
        path: pgsql/pgadmin4
      - name: minio-prod
        path: pgsql/minio/overlays/prod
      - name: minio-stg
        path: pgsql/minio/overlays/stg
      - name: minio-dev
        path: pgsql/minio/overlays/dev
  - list:
      elements:
      - name: wst-flyway-prod
        path: pgsql/wst-flyway/overlays/prod
        image: wst-flyway
        tag: main
      - name: wst-flyway-stg
        path: pgsql/wst-flyway/overlays/stg
        image: wst-flyway
        tag: stg
      - name: wst-flyway-dev
        path: pgsql/wst-flyway/overlays/dev
        image: wst-flyway
        tag: dev
      template:
        metadata:
          name: '{{name}}'
          annotations:
            argocd-image-updater.argoproj.io/image-list: "{{image}}=ghcr.io/x81k25/wst-flyway:{{tag}}"
            argocd-image-updater.argoproj.io/{{image}}.update-strategy: "digest"
            argocd-image-updater.argoproj.io/write-back-method: "git"
            argocd-image-updater.argoproj.io/git-branch: "main"
        spec:
          project: default
          source:
            repoURL: git@github.com:x81k25/k8s-manifests.git
            targetRevision: HEAD
            path: "{{path}}"
          destination:
            server: https://kubernetes.default.svc
            namespace: "pgsql"
          syncPolicy:
            automated:
              prune: true
              selfHeal: true
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: git@github.com:x81k25/k8s-manifests.git
        targetRevision: HEAD
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "pgsql"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true