apiVersion: apps/v1
kind: Deployment
metadata:
  name: profiles-kfam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profiles-kfam
  template:
    metadata:
      labels:
        app: profiles-kfam
    spec:
      serviceAccountName: kubeflow-sa
      containers:
      - name: profiles-kfam
        image: gcr.io/kubeflow-images-public/profile-controller:vmaster-g6e234a0a
        args: 
        - "--userid-header=kubeflow-userid"
        ports:
        - containerPort: 8081
        volumeMounts:
        - name: config-volume
          mountPath: /etc/profile-controller
      volumes:
      - name: config-volume
        configMap:
          name: profile-controller-config