apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
nameSuffix: -dev
commonLabels:
  variant: dev
patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: vpn-gateway
    spec:
      template:
        spec:
          containers:
          - name: vpn-gateway
            image: ghcr.io/x81k25/vpn-gateway:dev