apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
nameSuffix: -dev
commonLabels:
  variant: dev
patches:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: vpn-gateway
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: ghcr.io/x81k25/vpn-gateway:dev