apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
spec:
  project: default
  source:
    repoURL: # Your git repository URL needs to be added here
    targetRevision: HEAD
    path: postgres  # Assuming these files are in a 'postgres' directory
  destination:
    server: https://kubernetes.default.svc
    namespace: default  # The namespace where you want postgres deployed
  syncPolicy:
    automated:
      prune: true  # Automatically delete resources that are no longer defined in Git
      selfHeal: true  # Automatically sync if drift is detected
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /spec/volumeClaimTemplates/status  # Ignore PVC status changes