apiVersion: kustomize.config.k8s.io/v1beta1
commonAnnotations:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: postgres-x81
  maintainer: devops-team
commonLabels:
  app: postgres-x81
  environment: production
configurations:
  - nameReference:
      fieldSpecs:
        - kind: Deployment
          path: spec/template/spec/volumes/configMap/name
      kind: ConfigMap
  - fieldSpecs:
      - kind: Deployment
        path: spec/template/spec/volumes/secret/secretName
      kind: Secret
  - fieldSpecs:
      - kind: Deployment
        path: spec/template/spec/volumes/persistentVolumeClaim/claimName
      kind: PersistentVolumeClaim
images:
  - name: postgres
    newName: postgres
    newTag: '16.2'
kind: Kustomization
metadata:
  labels:
    argocd.argoproj.io/instance: postgres-x81
  namespace: postgres
namespace: postgres
resources:
  - configmap.yaml
  - deployment.yaml
  - networkpolicy.yaml
  - pv.yaml
  - pvc.yaml
  - secret.yaml
  - service.yaml