apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace where all resources will be created
namespace: postgres

# List all resources that should be deployed
resources:
  - pv.yaml
  - pvc.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - networkpolicy.yaml

# Common labels to be added to all resources
commonLabels:
  app: postgres-x81

# Common annotations
commonAnnotations:
  maintainer: "devops-team"
  argocd.argoproj.io/sync-wave: "1"

# ConfigMap configuration
configMapGenerator:
  - name: postgres-x81-config
    behavior: merge
    files:
      - postgresql.conf=configmap.yaml
    labels:
      app: postgres-x81

# Secret configuration
secretGenerator:
  - name: postgres-x81-secret
    behavior: merge
    files:
      - postgres-creds.yaml=secret.yaml
    labels:
      app: postgres-x81

# Images can be customized here if needed
# images:
# - name: postgres
#   newTag: 16.2

# Patches can be added here if needed for different environments
# patches:
# - path: patches/increase-replica-count.yaml
#   target:
#     kind: Deployment
#     name: postgres-x81