apiVersion: apps/v1
kind: Deployment
metadata:
  name: atd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atd
  template:
    metadata:
      labels:
        app: atd
    spec:
      securityContext:
        runAsUser: 1005
        runAsGroup: 1001
      containers:
      - name: vpn-sidecar
        image: ghcr.io/x81k25/automatic-transmission-daemon-vpn:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
          capabilities:
            add:
              - NET_ADMIN
        env:
        - name: VPN_USERNAME
          valueFrom:
            secretKeyRef:
              name: vpn-credentials
              key: username
        - name: VPN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: vpn-credentials
              key: password
        - name: VPN_CONFIG
          valueFrom:
            secretKeyRef:
              name: vpn-credentials
              key: config
      - name: automatic-transmission-daemon
        image: ghcr.io/x81k25/automatic-transmission-daemon:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9091
        env:
        - name: PUID
          value: "1005"
        - name: PGID
          value: "1001"
        volumeMounts:
        - name: complete-volume
          mountPath: /media-cache/complete
        - name: incomplete-volume
          mountPath: /media-cache/incomplete
      volumes:
      - name: complete-volume
        hostPath:
          path: /d/media-cache/ENV/complete
          type: DirectoryOrCreate
      - name: incomplete-volume
        hostPath:
          path: /d/media-cache/ENV/incomplete
          type: DirectoryOrCreate
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
        - 8.8.8.8
        - 8.8.4.4
      imagePullSecrets:
      - name: ghcr-pull-image-token