apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: route-through-vpn-dev
spec:
  podSelector:
    matchLabels:
      app: atd
      variant: dev
  policyTypes:
  - Egress
  egress:
  - to: []  # Allow all destinations for UDP tracker traffic
    ports:
    - protocol: UDP
      port: 1337
    - protocol: UDP
      port: 6969
    - protocol: UDP
      port: 80
    - protocol: UDP
      port: 451
  # Keep existing rules for HTTP proxy
  - to:
    - podSelector:
        matchLabels:
          app: vpn-gateway
          variant: dev
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
    ports:
    - protocol: UDP
      port: 53