apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-egress-dev
  namespace: media-dev
spec:
  podSelector:
    matchLabels:
      app: atd
      variant: dev
  policyTypes:
  - Egress
  egress:
  - to: [] # Allow all egress traffic