apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: route-through-vpn-dev
  namespace: media-dev
spec:
  podSelector:
    matchLabels:
      app: atd
      variant: dev
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: vpn-gateway
    ports:
    - protocol: TCP
      port: 8118
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53