# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test-app
  namespace: argocd-test
  labels:
    app: nginx-test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-test-app
  template:
    metadata:
      labels:
        app: nginx-test-app
    spec:
      containers:
      - name: nginx
        image: nginx:1.25.3
        ports:
        - containerPort: 80