# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: test-app-app-service
  namespace: argocd-test
spec:
  selector:
    app: nginx-test
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP