apiVersion: v1
kind: Service
metadata:
  name: cici-mind
  namespace: ai-ml
  labels:
    app: cici-mind
spec:
  type: NodePort
  ports:
  - port: 8765
    targetPort: 8765
    nodePort: 30211
  selector:
    app: cici-mind
