apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: automatic-transmission
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/x81k25/k8s-manifests.git  
    targetRevision: HEAD
    path: automatic-transmission-daemon
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false