apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- deployment.yaml
- service.yaml
- pv.yaml
- pvc.yaml

commonLabels:
  app: automatic-transmission
  part-of: media-services