apiVersion: v1
kind: PersistentVolume
metadata:
  name: transmission-media-cache
spec:
  capacity:
    storage: 938Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /d/media-cache
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - x81k25-server  # We'll need your actual node name here