apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-media-cache
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 938Gi