#./overlays/dev/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
nameSuffix: -stg
commonLabels:
  variant: stg
patches:
  - target:
      version: v1
      kind: Service
      name: atd
    patch: |-
      - op: replace
        path: /spec/ports/0/port
        value: 9092
      - op: replace
        path: /spec/ports/0/nodePort
        value: 30092
  - target:
      version: apps/v1
      kind: Deployment
      name: atd
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: ghcr.io/x81k25/automatic-transmission-daemon:stg
  - target:
      version: argoproj.io/v1alpha1
      kind: Application
      name: atd
    patch: |-
      - op: replace
        path: /spec/source/path
        value: overlays/stg
  - target:
      version: apps/v1
      kind: Deployment
      name: atd
    patch: |-
      - op: replace
        path: /spec/template/spec/volumes/0/hostPath/path
        value: /d/media-cache/stg/complete
      - op: replace
        path: /spec/template/spec/volumes/1/hostPath/path
        value: /d/media-cache/stg/incomplete