apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
namePrefix: atd-
nameSuffix: -stg
commonLabels:
  variant: stg
patchesStrategicMerge:
- |-
  apiVersion: v1
  kind: Service
  metadata:
    name: atd
  spec:
    ports:
    - port: 9092
      targetPort: 9091
      nodePort: 30092
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: atd
  spec:
    template:
      spec:
        containers:
        - name: automatic-transmission-daemon
          image: ghcr.io/x81k25/automatic-transmission-daemon:stg
- |-
  apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    name: atd
  spec:
    source:
      path: overlays/stg