#./overlays/stg/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
nameSuffix: -stg
commonLabels:
  variant: stg
patches:
- target:
    version: apps/v1
    kind: Deployment
    name: atd
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: ghcr.io/x81k25/automatic-transmission-daemon:stg
    - op: replace
      path: /spec/template/spec/volumes/0/hostPath/path
      value: /d/media-cache/stg/complete
    - op: replace
      path: /spec/template/spec/volumes/1/hostPath/path
      value: /d/media-cache/stg/incomplete
    - op: replace
      path: /spec/template/spec/containers/0/volumeMounts/0/mountPath
      value: /media-cache/stg/complete
    - op: replace
      path: /spec/template/spec/containers/0/volumeMounts/1/mountPath
      value: /media-cache/stg/incomplete
    - op: add
      path: /spec/template/spec/securityContext
      value:
        runAsUser: 1005
        runAsGroup: 1001