apiVersion: batch/v1
kind: CronJob
metadata:
  name: wst-flyway-restart
  namespace: pgsql
spec:
  schedule: "*/5 * * * *"  # Every 5 minutes
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: wst-flyway-restart-sa
          containers:
          - name: kubectl
            image: bitnami/kubectl:latest
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - |
              kubectl rollout restart deployment/wst-flyway -n pgsql
          restartPolicy: OnFailure