apiVersion: apps/v1
kind: Deployment
metadata:
  name: wst-flyway
  namespace: pgsql
  labels:
    app: wst-flyway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wst-flyway
  template:
    metadata:
      labels:
        app: wst-flyway
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      imagePullSecrets:
      - name: ghcr-pull-image-secret
      initContainers:
      - name: wst-flyway-migrate
        image: ghcr.io/x81k25/wst-flyway:sha-1dc332f
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: flyway-config
        - secretRef:
            name: flyway-secrets
        env:
        - name: FLYWAY_URL
          value: "jdbc:postgresql://$(FLYWAY_PGSQL_HOST):$(FLYWAY_PGSQL_PORT)/$(FLYWAY_PGSQL_DATABASE)"
        - name: FLYWAY_USER
          value: "$(FLYWAY_PGSQL_USERNAME)"
        - name: FLYWAY_PASSWORD
          value: "$(FLYWAY_PGSQL_PASSWORD)"
        args: ["migrate"]
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      containers:
      - name: wst-flyway-main
        image: ghcr.io/x81k25/wst-flyway:sha-1dc332f
        imagePullPolicy: Always
        command: ["sleep", "infinity"]
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "100m"
