apiVersion: v1
kind: Service
metadata:
  name: center-console
  labels:
    app: center-console
spec:
  type: NodePort
  ports:
  - port: 8501
    targetPort: 8501
    nodePort: 30850
  selector:
    app: center-console