# dagster/base/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dagster
imagePullSecrets:
- name: ghcr-pull-image-secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dagster
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch", "create", "delete"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "create", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs", "jobs/status"]
  verbs: ["get", "list", "watch", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dagster
subjects:
- kind: ServiceAccount
  name: dagster
roleRef:
  kind: Role
  name: dagster
  apiGroup: rbac.authorization.k8s.io